// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService 插件管理服务：扫描插件目录、读 manifest、启用/禁用
 * 注：本轮只做"发现 + 管理"，不真正执行插件代码（执行需要 JS runtime，留 P9+）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * DisablePlugin 禁用插件
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DisablePlugin(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.DisablePlugin", id);
}

/**
 * EnablePlugin 启用插件
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function EnablePlugin(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.EnablePlugin", id);
}

/**
 * GetPlugin 取单个插件的完整信息（含源码）
 * @param {string} id
 * @returns {$CancellablePromise<core$0.PluginInfo | null>}
 */
export function GetPlugin(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.GetPlugin", id);
}

/**
 * GetPluginsDir 返回插件目录绝对路径
 * @returns {$CancellablePromise<string>}
 */
export function GetPluginsDir() {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.GetPluginsDir");
}

/**
 * GrantTrust 授权某个插件以 full 信任等级运行。
 * 
 * 前置条件：插件 manifest 必须声明 trust=full。授权与当前源码哈希绑定——
 * 插件更新后哈希变化，授权自动失效，需要用户重新确认。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function GrantTrust(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.GrantTrust", id);
}

/**
 * ListPlugins 扫描插件目录，列出所有已发现的插件。
 * 
 * 历史签名是 ListPlugins(rescan bool)，但 rescan 是死参数——实现没有任何缓存，
 * 传 true/false 行为完全一致，只是在伪装"可跳过扫描"的语义。已移除该参数，
 * 让契约如实反映"每次调用都读盘"这一事实。
 * @returns {$CancellablePromise<core$0.PluginInfo[] | null>}
 */
export function ListPlugins() {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.ListPlugins");
}

/**
 * LoadPluginData 读取插件私有数据。
 * 数据不存在时返回空串（不是错误）——插件首次运行时本来就没有数据。
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function LoadPluginData(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.LoadPluginData", id);
}

/**
 * RevokeTrust 撤销某个插件的 full 信任授权，插件立即回落到沙箱等级运行。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RevokeTrust(id) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.RevokeTrust", id);
}

/**
 * SavePluginData 保存插件私有数据（调用方负责序列化，本服务只做透传存储）
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SavePluginData(id, data) {
    return $Call.ByName("github.com/notevault/notevault/internal/plugin.PluginService.SavePluginData", id, data);
}
