// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveService 提供归档管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveFile 归档文件（移动到 .archive 目录）
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.ArchivedFile | null>}
 */
export function ArchiveFile(workspacePath, relativePath) {
    return $Call.ByID(4280765932, workspacePath, relativePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetArchivedFiles 获取所有归档文件
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.ArchivedFile | null)[]>}
 */
export function GetArchivedFiles(workspacePath) {
    return $Call.ByID(3231169153, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsArchived 检查文件是否已归档
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<boolean>}
 */
export function IsArchived(workspacePath, relativePath) {
    return $Call.ByID(1490294866, workspacePath, relativePath);
}

/**
 * UnarchiveFile 取消归档（移回原位置）
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<void>}
 */
export function UnarchiveFile(workspacePath, relativePath) {
    return $Call.ByID(1116013497, workspacePath, relativePath);
}

// Private type creation functions
const $$createType0 = $models.ArchivedFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
