// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchiveService 提供归档管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveFile 归档文件（移动到 .archive 目录）
 */
export function ArchiveFile(workspacePath: string, relativePath: string): $CancellablePromise<$models.ArchivedFile | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ArchiveService.ArchiveFile", workspacePath, relativePath);
}

/**
 * GetArchivedFiles 获取所有归档文件
 */
export function GetArchivedFiles(workspacePath: string): $CancellablePromise<($models.ArchivedFile | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ArchiveService.GetArchivedFiles", workspacePath);
}

/**
 * IsArchived 检查文件是否已归档
 */
export function IsArchived(workspacePath: string, relativePath: string): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ArchiveService.IsArchived", workspacePath, relativePath);
}

/**
 * UnarchiveFile 取消归档（移回原位置）
 */
export function UnarchiveFile(workspacePath: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ArchiveService.UnarchiveFile", workspacePath, relativePath);
}
