// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BaseService 提供结构化视图（Bases）能力：把工作区里的 Markdown
 * 当成一张可查询的表，按 front matter 属性 / 标签 / 待办 / 文件元数据筛选、排序、分组。
 * 
 * 设计要点：
 *   - **不建独立数据库。** 属性从文件现读现算（带 30s TTL 缓存），
 *     笔记永远是唯一事实来源；用外部编辑器改了 front matter 也不会数据不一致。
 *   - **视图定义是普通文件。** `.notevault/bases/*.nvbase` 是可读 JSON，
 *     可以进 git、可以手改、可以在设备间同步。
 *   - **查询永不报错。** 属性名打错、正则写坏、类型对不上，一律降级 + 冒 warning，
 *     绝不用一个报错弹窗打断用户的探索过程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteBase 删除一个视图定义。
 * @param {string} workspacePath
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBase(workspacePath, name) {
    return $Call.ByID(3332327047, workspacePath, name);
}

/**
 * InvalidateCache 清除属性索引缓存。
 * 
 * 文件保存 / 删除 / 切工作区后由上层调用，否则用户改完 front matter
 * 最多要等 30 秒才在视图里看到变化。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateCache(workspacePath) {
    return $Call.ByID(1707934602, workspacePath);
}

/**
 * ListBases 列出工作区里所有已保存的视图定义。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.BaseSummary | null)[]>}
 */
export function ListBases(workspacePath) {
    return $Call.ByID(522850925, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListOperators 返回全部可用运算符，供前端下拉。
 * 
 * 从后端返回而不是前端硬编码：运算符集合是查询语义的一部分，
 * 加一个运算符时只该改一处。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOperators() {
    return $Call.ByID(3424881998).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListProperties 返回工作区里所有可用属性及统计信息，供前端属性选择器使用。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.PropertyMeta | null)[]>}
 */
export function ListProperties(workspacePath) {
    return $Call.ByID(3231124264, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListTemplates 返回内置模板，覆盖几个最常见的知识库用法。
 * 
 * 模板不是装饰：Bases 这类功能的核心难点是"我不知道能用它干什么"，
 * 给出几个立刻能跑的例子比写一页文档有效。
 * @returns {$CancellablePromise<($models.BuiltinTemplate | null)[]>}
 */
export function ListTemplates() {
    return $Call.ByID(1459865180).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListViewTypes 返回全部视图类型。
 * @returns {$CancellablePromise<string[]>}
 */
export function ListViewTypes() {
    return $Call.ByID(2186695621).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * LoadBase 读取一个视图的完整定义。
 * @param {string} workspacePath
 * @param {string} name
 * @returns {$CancellablePromise<$models.BaseDef | null>}
 */
export function LoadBase(workspacePath, name) {
    return $Call.ByID(3567648148, workspacePath, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * NewBaseTemplate 返回一份可直接保存的空白视图定义。
 * 
 * 前端"新建视图"点下去就能得到一个能跑的东西，而不是一张空表单——
 * 空表单是查询工具最大的上手门槛。
 * @param {string} name
 * @returns {$CancellablePromise<$models.BaseDef | null>}
 */
export function NewBaseTemplate(name) {
    return $Call.ByID(1859222534, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * RenameBase 重命名视图（同时改 Name 字段与文件名）。
 * @param {string} workspacePath
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameBase(workspacePath, oldName, newName) {
    return $Call.ByID(3227276734, workspacePath, oldName, newName);
}

/**
 * RunBase 在给定定义上执行查询（不要求已保存）。
 * 
 * 前端编辑筛选条件时走这条路径做实时预览：改一个条件就重跑一次，
 * 不需要先保存到磁盘。
 * @param {string} workspacePath
 * @param {$models.BaseDef} def
 * @param {string} viewID
 * @returns {$CancellablePromise<$models.BaseResult | null>}
 */
export function RunBase(workspacePath, def, viewID) {
    return $Call.ByID(1281680391, workspacePath, def, viewID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * RunSavedBase 读取已保存的视图定义并执行。
 * @param {string} workspacePath
 * @param {string} name
 * @param {string} viewID
 * @returns {$CancellablePromise<$models.BaseResult | null>}
 */
export function RunSavedBase(workspacePath, name, viewID) {
    return $Call.ByID(2109836756, workspacePath, name, viewID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * SaveBase 保存（新建或覆盖）一个视图定义。
 * @param {string} workspacePath
 * @param {$models.BaseDef} def
 * @returns {$CancellablePromise<void>}
 */
export function SaveBase(workspacePath, def) {
    return $Call.ByID(1608654573, workspacePath, def);
}

// Private type creation functions
const $$createType0 = $models.BaseSummary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.PropertyMeta.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.BuiltinTemplate.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.BaseDef.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.BaseResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
