// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BaseService 提供结构化视图（Bases）能力：把工作区里的 Markdown
 * 当成一张可查询的表，按 front matter 属性 / 标签 / 待办 / 文件元数据筛选、排序、分组。
 * 
 * 设计要点：
 *   - **不建独立数据库。** 属性从文件现读现算（带 30s TTL 缓存），
 *     笔记永远是唯一事实来源；用外部编辑器改了 front matter 也不会数据不一致。
 *   - **视图定义是普通文件。** `.notevault/bases/*.nvbase` 是可读 JSON，
 *     可以进 git、可以手改、可以在设备间同步。
 *   - **查询永不报错。** 属性名打错、正则写坏、类型对不上，一律降级 + 冒 warning，
 *     绝不用一个报错弹窗打断用户的探索过程。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteBase 删除一个视图定义。
 * @param {string} workspacePath
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBase(workspacePath, name) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.DeleteBase", workspacePath, name);
}

/**
 * InvalidateCache 清除属性索引缓存。
 * 
 * 文件保存 / 删除 / 切工作区后由上层调用，否则用户改完 front matter
 * 最多要等 30 秒才在视图里看到变化。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateCache(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.InvalidateCache", workspacePath);
}

/**
 * ListBases 列出工作区里所有已保存的视图定义。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.BaseSummary | null)[] | null>}
 */
export function ListBases(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.ListBases", workspacePath);
}

/**
 * ListOperators 返回全部可用运算符，供前端下拉。
 * 
 * 从后端返回而不是前端硬编码：运算符集合是查询语义的一部分，
 * 加一个运算符时只该改一处。
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ListOperators() {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.ListOperators");
}

/**
 * ListProperties 返回工作区里所有可用属性及统计信息，供前端属性选择器使用。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.PropertyMeta | null)[] | null>}
 */
export function ListProperties(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.ListProperties", workspacePath);
}

/**
 * ListTemplates 返回内置模板，覆盖几个最常见的知识库用法。
 * 
 * 模板不是装饰：Bases 这类功能的核心难点是"我不知道能用它干什么"，
 * 给出几个立刻能跑的例子比写一页文档有效。
 * @returns {$CancellablePromise<($models.BuiltinTemplate | null)[] | null>}
 */
export function ListTemplates() {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.ListTemplates");
}

/**
 * ListViewTypes 返回全部视图类型。
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ListViewTypes() {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.ListViewTypes");
}

/**
 * LoadBase 读取一个视图的完整定义。
 * @param {string} workspacePath
 * @param {string} name
 * @returns {$CancellablePromise<$models.BaseDef | null>}
 */
export function LoadBase(workspacePath, name) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.LoadBase", workspacePath, name);
}

/**
 * NewBaseTemplate 返回一份可直接保存的空白视图定义。
 * 
 * 前端"新建视图"点下去就能得到一个能跑的东西，而不是一张空表单——
 * 空表单是查询工具最大的上手门槛。
 * @param {string} name
 * @returns {$CancellablePromise<$models.BaseDef | null>}
 */
export function NewBaseTemplate(name) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.NewBaseTemplate", name);
}

/**
 * RenameBase 重命名视图（同时改 Name 字段与文件名）。
 * @param {string} workspacePath
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameBase(workspacePath, oldName, newName) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.RenameBase", workspacePath, oldName, newName);
}

/**
 * RunBase 在给定定义上执行查询（不要求已保存）。
 * 
 * 前端编辑筛选条件时走这条路径做实时预览：改一个条件就重跑一次，
 * 不需要先保存到磁盘。
 * @param {string} workspacePath
 * @param {$models.BaseDef} def
 * @param {string} viewID
 * @returns {$CancellablePromise<$models.BaseResult | null>}
 */
export function RunBase(workspacePath, def, viewID) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.RunBase", workspacePath, def, viewID);
}

/**
 * RunSavedBase 读取已保存的视图定义并执行。
 * @param {string} workspacePath
 * @param {string} name
 * @param {string} viewID
 * @returns {$CancellablePromise<$models.BaseResult | null>}
 */
export function RunSavedBase(workspacePath, name, viewID) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.RunSavedBase", workspacePath, name, viewID);
}

/**
 * SaveBase 保存（新建或覆盖）一个视图定义。
 * @param {string} workspacePath
 * @param {$models.BaseDef} def
 * @returns {$CancellablePromise<void>}
 */
export function SaveBase(workspacePath, def) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.BaseService.SaveBase", workspacePath, def);
}
