// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClipperService 本地剪藏 HTTP 服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigureAI 注入对话模型配置（由前端在 AI 设置就绪/变更时调用）。
 * 四参全空视为关闭 AI 摘要。
 */
export function ConfigureAI(apiKey: string, baseURL: string, model: string, protocol: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ClipperService.ConfigureAI", apiKey, baseURL, model, protocol);
}

/**
 * Start 加载/生成 Token 并在 127.0.0.1 上开始监听。非阻塞：Serve 在后台 goroutine。
 * 端口被占用等监听失败原样返回错误，由调用方决定是否降级（应用不因此退出）。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ClipperService.Start");
}

/**
 * Status 返回当前运行状态与 Token（Token 供用户复制进浏览器扩展）。
 */
export function Status(): $CancellablePromise<$models.ClipperStatus> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ClipperService.Status");
}

/**
 * Stop 优雅停机（应用退出时调用）。未启动时是 no-op。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ClipperService.Stop");
}
