// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompileService 知识编译流水线。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompileAll 编译 Inbox 内全部笔记。
 * 单篇失败不影响其他篇；返回每篇结果或错误，由调用方决定如何处理。
 * @param {string} workspacePath
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} model
 * @returns {$CancellablePromise<[($models.CompileResult | null)[] | null, any[] | null]>}
 */
export function CompileAll(workspacePath, apiKey, baseURL, model) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.CompileAll", workspacePath, apiKey, baseURL, model);
}

/**
 * CompileNote 编译单篇笔记：先建快照，再调 AI，最后把更新后的笔记移动到 Compiled。
 * relativePath 必须位于 Inbox 目录内，否则报错（避免误编译库内其他笔记）。
 * @param {string} workspacePath
 * @param {string} relativePath
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} model
 * @returns {$CancellablePromise<$models.CompileResult | null>}
 */
export function CompileNote(workspacePath, relativePath, apiKey, baseURL, model) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.CompileNote", workspacePath, relativePath, apiKey, baseURL, model);
}

/**
 * ListInbox 列出 Inbox 目录下的全部 Markdown 笔记（相对路径，含 Inbox 前缀）。
 * 目录不存在时返回空切片而非错误。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<string[] | null>}
 */
export function ListInbox(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.ListInbox", workspacePath);
}
