// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompileService 知识编译流水线。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompileAll 编译 Inbox 内全部笔记。
 * 单篇失败不影响其他篇；失败项进入 Errors 而非顶层 error，
 * 顶层 error 仅代表「连 Inbox 都列不出来」这类致命错误。
 * @param {string} workspacePath
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} model
 * @returns {$CancellablePromise<$models.CompileAllResult | null>}
 */
export function CompileAll(workspacePath, apiKey, baseURL, model) {
    return $Call.ByID(3324600155, workspacePath, apiKey, baseURL, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CompileNote 编译单篇笔记：先建快照，再调 AI，最后把更新后的笔记移动到 Compiled。
 * relativePath 必须位于 Inbox 目录内，否则报错（避免误编译库内其他笔记）。
 * @param {string} workspacePath
 * @param {string} relativePath
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} model
 * @returns {$CancellablePromise<$models.CompileResult | null>}
 */
export function CompileNote(workspacePath, relativePath, apiKey, baseURL, model) {
    return $Call.ByID(2607667828, workspacePath, relativePath, apiKey, baseURL, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListInbox 列出 Inbox 目录下的全部 Markdown 笔记（相对路径，含 Inbox 前缀）。
 * 目录不存在时返回空切片而非错误。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<string[]>}
 */
export function ListInbox(workspacePath) {
    return $Call.ByID(4125408681, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CompileAllResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CompileResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
