// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CompileService 知识编译流水线。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompileAll 编译 Inbox 内全部笔记。
 * 单篇失败不影响其他篇；失败项进入 Errors 而非顶层 error，
 * 顶层 error 仅代表「连 Inbox 都列不出来」这类致命错误。
 */
export function CompileAll(workspacePath: string, apiKey: string, baseURL: string, model: string, protocol: string): $CancellablePromise<$models.CompileAllResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.CompileAll", workspacePath, apiKey, baseURL, model, protocol);
}

/**
 * CompileNote 编译单篇笔记：先建快照，再调 AI，最后把更新后的笔记移动到 Compiled。
 * relativePath 必须位于 Inbox 目录内，否则报错（避免误编译库内其他笔记）。
 */
export function CompileNote(workspacePath: string, relativePath: string, apiKey: string, baseURL: string, model: string, protocol: string): $CancellablePromise<$models.CompileResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.CompileNote", workspacePath, relativePath, apiKey, baseURL, model, protocol);
}

/**
 * ListInbox 列出 Inbox 目录下的全部 Markdown 笔记（相对路径，含 Inbox 前缀）。
 * 目录不存在时返回空切片而非错误。
 */
export function ListInbox(workspacePath: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CompileService.ListInbox", workspacePath);
}
