// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CredentialService 把 API Key 等敏感凭据从 localStorage 迁到系统凭据库（P2-5）。
 * 
 * 为什么做成 Wails 服务而不是继续留在前端：凭据库只能由宿主进程访问，
 * 前端拿到的只是"读写这个 key 的能力"，而且 value 不再落进 WebView 的
 * localStorage——渲染进程被攻破也读不到明文。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * DeleteCredential 删除密钥。不存在时幂等成功。
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCredential(key) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CredentialService.DeleteCredential", key);
}

/**
 * GetCredential 读取密钥。不存在时返回 ("", nil)。
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetCredential(key) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CredentialService.GetCredential", key);
}

/**
 * SaveCredential 保存密钥。value 为空串等价于删除——"清空输入框"是前端
 * 最自然的表达，不该强迫调用方记住还要再调一次 Delete。
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveCredential(key, value) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.CredentialService.SaveCredential", key, value);
}
