// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService 提供笔记导出能力
 * 设计原则：导出逻辑零外部依赖（仅使用标准库），Markdown→HTML 的渲染由前端完成，
 * Go 端只负责把内容写入用户选定的目标路径（或打包为 zip）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportNoteMarkdown 将单个笔记（按相对路径）复制导出到 destPath
 * @param {string} workspacePath
 * @param {string} relPath
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportNoteMarkdown(workspacePath, relPath, destPath) {
    return $Call.ByID(2116433417, workspacePath, relPath, destPath);
}

/**
 * ExportWorkspaceMarkdown 将工作区中所有 Markdown 文件打包为 zip 写入 destPath
 * destPath 为目标 zip 文件路径（若未以 .zip 结尾会自动补上）
 * @param {string} workspacePath
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportWorkspaceMarkdown(workspacePath, destPath) {
    return $Call.ByID(3872025128, workspacePath, destPath);
}

/**
 * SaveText 将任意文本内容写入绝对路径（用于单文件 HTML 等富文本导出）
 * @param {string} destPath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveText(destPath, content) {
    return $Call.ByID(507355236, destPath, content);
}
