// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 管理文件的读取、创建、保存和删除
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFile 创建新文件
 * workspacePath: 工作区根目录
 * relativePath: 相对于工作区根目录的文件路径（含文件名）
 * content: 文件初始内容
 */
export function CreateFile(workspacePath: string, relativePath: string, content: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.CreateFile", workspacePath, relativePath, content);
}

/**
 * CreateFolder 创建文件夹
 * workspacePath: 工作区根目录
 * relativePath: 相对于工作区根目录的文件夹路径
 */
export function CreateFolder(workspacePath: string, relativePath: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.CreateFolder", workspacePath, relativePath);
}

/**
 * DeleteFile 删除文件（直接删除，不进回收站）
 * workspacePath: 工作区根目录
 * relativePath: 相对于工作区根目录的文件路径
 */
export function DeleteFile(workspacePath: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.DeleteFile", workspacePath, relativePath);
}

/**
 * GetFileTree 获取指定工作区的文件树
 * workspacePath: 工作区根目录绝对路径
 * 返回文件树的根节点列表
 */
export function GetFileTree(workspacePath: string): $CancellablePromise<($models.FileNode | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.GetFileTree", workspacePath);
}

/**
 * ReadFile 读取文件内容
 * workspacePath: 工作区根目录
 * relativePath: 相对于工作区根目录的文件路径
 */
export function ReadFile(workspacePath: string, relativePath: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.ReadFile", workspacePath, relativePath);
}

/**
 * RenameFile 重命名文件或文件夹
 * workspacePath: 工作区根目录
 * oldRelativePath: 旧的相对路径
 * newName: 新名称（不含路径）
 */
export function RenameFile(workspacePath: string, oldRelativePath: string, newName: string): $CancellablePromise<$models.FileNode | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.RenameFile", workspacePath, oldRelativePath, newName);
}

/**
 * SaveFile 保存文件内容（覆盖写入）
 * workspacePath: 工作区根目录
 * relativePath: 相对于工作区根目录的文件路径
 * content: 文件内容
 */
export function SaveFile(workspacePath: string, relativePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.SaveFile", workspacePath, relativePath, content);
}

/**
 * SaveImage 保存图片到工作区的 assets 文件夹
 * workspacePath: 工作区根目录
 * fileName: 图片文件名
 * data: 图片二进制数据
 * 返回图片相对于工作区的路径
 */
export function SaveImage(workspacePath: string, fileName: string, data: string | null): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.FileService.SaveImage", workspacePath, fileName, data);
}
