// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService 提供 git init / .gitignore / 一键提交。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CommitAll 把全部变更（含未跟踪文件）提交为一个 commit，返回给用户的提示文案。
 * 没有可提交内容时返回 ("没有可提交的变更", nil)——这是正常路径，不是错误。
 */
export function CommitAll(workspacePath: string, message: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.GitService.CommitAll", workspacePath, message);
}

/**
 * EnsureGitignore 在工作区生成默认 .gitignore。
 * 已存在时不覆盖（用户可能有自己的规则），返回是否新建。
 */
export function EnsureGitignore(workspacePath: string): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.GitService.EnsureGitignore", workspacePath);
}

/**
 * InitRepo 把工作区初始化为 git 仓库（幂等：已是仓库时不动），并顺手补 .gitignore。
 */
export function InitRepo(workspacePath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.GitService.InitRepo", workspacePath);
}

/**
 * Status 返回工作区 Git 概况。任何一步失败都降级为「能力缺失」而非报错：
 * 前端拿到 false/0 就能渲染出对应的引导 UI，不需要处理错误分支。
 */
export function Status(workspacePath: string): $CancellablePromise<$models.GitStatus | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.GitService.Status", workspacePath);
}
