// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GraphService 提供知识图谱（双向链接关系）构建能力
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetGraph 扫描工作区，构建笔记之间的关系图谱
 * workspacePath: 工作区根目录
 * @param {string} workspacePath
 * @returns {$CancellablePromise<$models.GraphData | null>}
 */
export function GetGraph(workspacePath) {
    return $Call.ByID(1403840634, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLinkCandidates 为编辑器的 [[ 自动补全提供候选。
 * query 是用户输入的链接文本（不含 [[ 与 ]]）：
 *   - ""        → 所有 markdown 文件（限前 maxLinkCandidates 条）
 *   - "foo"     → 文件名 / 路径含 foo 的文件
 *   - "foo#"    → foo 文件内的全部标题
 *   - "foo#bar" → foo 文件内标题含 bar 的标题
 *   - "#bar"    → 所有文件内标题含 bar 的标题
 * 
 * 与 GetGraph 同口径：大小写不敏感、跳过隐藏目录。
 * @param {string} workspacePath
 * @param {string} query
 * @returns {$CancellablePromise<($models.LinkCandidate | null)[]>}
 */
export function GetLinkCandidates(workspacePath, query) {
    return $Call.ByID(1535785272, workspacePath, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GraphData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LinkCandidate.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
