// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GraphService 提供知识图谱（双向链接关系）构建能力
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetGraph 扫描工作区，构建笔记之间的关系图谱
 * workspacePath: 工作区根目录
 */
export function GetGraph(workspacePath: string): $CancellablePromise<$models.GraphData | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.GraphService.GetGraph", workspacePath);
}
