// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService 负责从外部来源导入笔记数据
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImportMarkdownFolder 将文件夹中的 Markdown 文件导入到工作区
 * srcDir: 源文件夹绝对路径
 * workspacePath: 目标工作区根目录绝对路径
 * opts: 导入选项（空值使用默认）
 * 
 * 这是同步版本，行为与历史完全一致，供脚本化调用与测试使用。
 * 前端的大库导入应改用 ImportMarkdownFolderAsync。
 */
export function ImportMarkdownFolder(srcDir: string, workspacePath: string, opts: $models.ImportOptions): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ImportService.ImportMarkdownFolder", srcDir, workspacePath, opts);
}

/**
 * ImportMarkdownFolderAsync 异步导入文件夹，立即返回任务 ID。
 * 
 * 返回的是任务 ID 而不是结果：结果通过 task:finished 事件推送，
 * 前端也可以随时用 TaskService.GetTask 查询。
 * 
 * 导入期间前端 UI 不被阻塞，用户可以取消（TaskService.Cancel）。
 * 取消后已写入的文件会保留——导入是逐文件落盘的，中途停下会让工作区处于
 * "部分导入"状态，这一点前端必须如实告知用户，而不是假装什么都没发生。
 */
export function ImportMarkdownFolderAsync(srcDir: string, workspacePath: string, opts: $models.ImportOptions): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ImportService.ImportMarkdownFolderAsync", srcDir, workspacePath, opts);
}

/**
 * ImportZip 将 zip 压缩包中的 Markdown 文件导入到工作区
 * zipPath: zip 文件绝对路径
 * workspacePath: 目标工作区根目录绝对路径
 */
export function ImportZip(zipPath: string, workspacePath: string, opts: $models.ImportOptions): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ImportService.ImportZip", zipPath, workspacePath, opts);
}
