// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService 负责从外部来源导入笔记数据
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImportMarkdownFolder 将文件夹中的 Markdown 文件导入到工作区
 * srcDir: 源文件夹绝对路径
 * workspacePath: 目标工作区根目录绝对路径
 * opts: 导入选项（空值使用默认）
 */
export function ImportMarkdownFolder(srcDir: string, workspacePath: string, opts: $models.ImportOptions): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ImportService.ImportMarkdownFolder", srcDir, workspacePath, opts);
}

/**
 * ImportZip 将 zip 压缩包中的 Markdown 文件导入到工作区
 * zipPath: zip 文件绝对路径
 * workspacePath: 目标工作区根目录绝对路径
 */
export function ImportZip(zipPath: string, workspacePath: string, opts: $models.ImportOptions): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ImportService.ImportZip", zipPath, workspacePath, opts);
}
