// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ArchiveService from "./archiveservice.js";
import * as BaseService from "./baseservice.js";
import * as CompileService from "./compileservice.js";
import * as CredentialService from "./credentialservice.js";
import * as ExportService from "./exportservice.js";
import * as FileService from "./fileservice.js";
import * as GitService from "./gitservice.js";
import * as GraphService from "./graphservice.js";
import * as ImportService from "./importservice.js";
import * as LLMConfigService from "./llmconfigservice.js";
import * as QnAService from "./qnaservice.js";
import * as ReminderService from "./reminderservice.js";
import * as SearchService from "./searchservice.js";
import * as SnapshotService from "./snapshotservice.js";
import * as SummarizeService from "./summarizeservice.js";
import * as TagService from "./tagservice.js";
import * as TaskService from "./taskservice.js";
import * as TemplateService from "./templateservice.js";
import * as TodoService from "./todoservice.js";
import * as TrashService from "./trashservice.js";
import * as WorkspaceService from "./workspaceservice.js";
export {
    ArchiveService,
    BaseService,
    CompileService,
    CredentialService,
    ExportService,
    FileService,
    GitService,
    GraphService,
    ImportService,
    LLMConfigService,
    QnAService,
    ReminderService,
    SearchService,
    SnapshotService,
    SummarizeService,
    TagService,
    TaskService,
    TemplateService,
    TodoService,
    TrashService,
    WorkspaceService
};

export {
    PropKind,
    RerankProvider,
    TaskStatus
} from "./models.js";

import * as $models from "./models.js";

/**
 * ArchivedFile 表示一个归档文件
 * @typedef {$models.ArchivedFile} ArchivedFile
 */

/**
 * BaseCell 是表格里的一个单元格。
 * 
 * 同时带 Display 和结构化字段：Display 给前端直接渲染，
 * Kind/List/Num 给前端做类型化渲染（标签做成 chip、数字右对齐、布尔画勾）。
 * @typedef {$models.BaseCell} BaseCell
 */

/**
 * BaseDef 是一个 .nvbase 文件的完整内容。
 * 
 * 命名没跟 schema.BaseDefinition 一致（那个是 Descriptor 变量名），
 * 避免同名标识符在两个包里指代不同东西。
 * @typedef {$models.BaseDef} BaseDef
 */

/**
 * BaseFilter 是一条筛选条件。
 * 
 * Value 用字符串承载而不是 any：这个结构要穿过 JSON 落盘、再穿过 Wails 到前端，
 * any 在这条链路上会退化成 float64/string/bool，类型信息反而更乱。
 * 统一用字符串存原文，比较时按**目标属性的类型**强转 —— 类型的权威来源是数据，不是查询。
 * @typedef {$models.BaseFilter} BaseFilter
 */

/**
 * BaseFilterGroup 是可嵌套的条件组。
 * @typedef {$models.BaseFilterGroup} BaseFilterGroup
 */

/**
 * BaseGroup 是分组结果的一组。
 * @typedef {$models.BaseGroup} BaseGroup
 */

/**
 * BaseResult 是一次查询的完整输出。
 * @typedef {$models.BaseResult} BaseResult
 */

/**
 * BaseRow 是查询结果的一行（一篇笔记）。
 * @typedef {$models.BaseRow} BaseRow
 */

/**
 * BaseSort 是一条排序规则。
 * @typedef {$models.BaseSort} BaseSort
 */

/**
 * BaseSummary 是视图列表项（不含完整筛选配置，列表页不需要）。
 * @typedef {$models.BaseSummary} BaseSummary
 */

/**
 * BaseView 是一个视图配置。
 * @typedef {$models.BaseView} BaseView
 */

/**
 * BuiltinTemplate 描述一个内置模板。
 * @typedef {$models.BuiltinTemplate} BuiltinTemplate
 */

/**
 * CompileAllResult 是 CompileAll 的聚合结果，专为 Wails 绑定设计：
 * 返回单一结构体 + error（而非 Go 惯用的 (results, []error) 双返回值）。
 * 原因：Wails 会把多返回值序列化为元组，而 []error 是接口切片，
 * 每个 error 经 JSON 会退化成 {}，前端拿不到任何错误信息。
 * 这里用结构化的 CompileErrorItem 承载「路径 + 消息」，前端可逐条展示。
 * @typedef {$models.CompileAllResult} CompileAllResult
 */

/**
 * CompileErrorItem 单篇编译失败的路径与原因。
 * @typedef {$models.CompileErrorItem} CompileErrorItem
 */

/**
 * CompileOutput 是「知识编译」的结构化产出。
 * @typedef {$models.CompileOutput} CompileOutput
 */

/**
 * CompileResult 单篇笔记的编译结果。
 * @typedef {$models.CompileResult} CompileResult
 */

/**
 * DiffOp 表示 diff 中的一行操作
 * @typedef {$models.DiffOp} DiffOp
 */

/**
 * FileNode 表示文件树中的一个节点（文件或文件夹）
 * @typedef {$models.FileNode} FileNode
 */

/**
 * GitStatus 是工作区的 Git 概况，供前端决定展示「初始化」还是「提交」。
 * @typedef {$models.GitStatus} GitStatus
 */

/**
 * GraphData 知识图谱数据
 * @typedef {$models.GraphData} GraphData
 */

/**
 * GraphEdge 表示一条双向链接
 * @typedef {$models.GraphEdge} GraphEdge
 */

/**
 * GraphNode 表示知识图谱中的一个笔记节点
 * @typedef {$models.GraphNode} GraphNode
 */

/**
 * ImportOptions 导入选项
 * @typedef {$models.ImportOptions} ImportOptions
 */

/**
 * ImportResult 导入结果统计
 * @typedef {$models.ImportResult} ImportResult
 */

/**
 * LLMEndpointPreset 描述一个可一键填入的端点预设。
 * @typedef {$models.LLMEndpointPreset} LLMEndpointPreset
 */

/**
 * LLMProbeResult 连通性自检结果。
 * @typedef {$models.LLMProbeResult} LLMProbeResult
 */

/**
 * LinkCandidate 是编辑器 [[ 自动补全的候选项。
 * @typedef {$models.LinkCandidate} LinkCandidate
 */

/**
 * PropertyMeta 描述工作区里一个属性的统计信息，供前端属性选择器使用。
 * @typedef {$models.PropertyMeta} PropertyMeta
 */

/**
 * QnACitation 表示回答中引用的一处知识库内容
 * @typedef {$models.QnACitation} QnACitation
 */

/**
 * QnAResponse 是一次问答的完整结果
 * @typedef {$models.QnAResponse} QnAResponse
 */

/**
 * Reminder 表示一个提醒
 * @typedef {$models.Reminder} Reminder
 */

/**
 * RerankConfig 是 rerank 端点的连接配置（与 embedding / LLM 配置相互独立）。
 * @typedef {$models.RerankConfig} RerankConfig
 */

/**
 * SearchIndexStats 描述索引的覆盖情况，供状态栏提示（P0-5）
 * @typedef {$models.SearchIndexStats} SearchIndexStats
 */

/**
 * SearchResult 表示一个搜索结果
 * @typedef {$models.SearchResult} SearchResult
 */

/**
 * Snapshot 表示一份历史版本的元数据（内容存在 objects 里，按 Hash 寻址）
 * @typedef {$models.Snapshot} Snapshot
 */

/**
 * SnapshotDiff 是某个快照与目标版本（另一快照或当前文件）的差异
 * @typedef {$models.SnapshotDiff} SnapshotDiff
 */

/**
 * SnapshotFileSummary 按文件聚合的快照概览，用于时间机器面板左侧文件列表
 * @typedef {$models.SnapshotFileSummary} SnapshotFileSummary
 */

/**
 * SnapshotRestoreResult 恢复结果。BackupID 是恢复前自动打的安全备份，
 * 让「恢复错了」也能再退回去——AI/批量改写场景下这一步是刚需。
 * @typedef {$models.SnapshotRestoreResult} SnapshotRestoreResult
 */

/**
 * SnapshotStats 历史库占用概览
 * @typedef {$models.SnapshotStats} SnapshotStats
 */

/**
 * TagFileInfo 表示包含某个标签的文件信息
 * @typedef {$models.TagFileInfo} TagFileInfo
 */

/**
 * TagInfo 表示一个标签及其使用次数
 * @typedef {$models.TagInfo} TagInfo
 */

/**
 * TaskInfo 是任务的对外快照（会被 Wails 序列化成前端 TS 类型）。
 * @typedef {$models.TaskInfo} TaskInfo
 */

/**
 * TemplateInfo 描述一个可用模板。
 * @typedef {$models.TemplateInfo} TemplateInfo
 */

/**
 * TodoItem 表示一个待办事项
 * @typedef {$models.TodoItem} TodoItem
 */

/**
 * TrashedFile 表示回收站中的文件
 * @typedef {$models.TrashedFile} TrashedFile
 */

/**
 * Workspace 表示一个知识库工作区
 * @typedef {$models.Workspace} Workspace
 */
