// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LLMConfigService 提供端点预设与连通性自检。
 * 独立成一个服务而不是挂在 SummarizeService 上：
 * 自检要同时服务于「AI 总结」「知识问答」以及将来的 embedding 配置，
 * 挂在任一功能服务上都会让依赖方向变歪。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Presets 返回内置端点预设列表。
 * @returns {$CancellablePromise<$models.LLMEndpointPreset[] | null>}
 */
export function Presets() {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.Presets");
}

/**
 * Probe 对端点做连通性自检。
 * 用 GET /models 而不是发一次真实的 chat 请求：前者不消耗 token、不产生费用，
 * 且能顺带把可用模型列表带回来给前端做下拉。
 * @param {string} apiKey
 * @param {string} baseURL
 * @returns {$CancellablePromise<$models.LLMProbeResult | null>}
 */
export function Probe(apiKey, baseURL) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.Probe", apiKey, baseURL);
}
