// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LLMConfigService 提供端点预设与连通性自检。
 * 独立成一个服务而不是挂在 SummarizeService 上：
 * 自检要同时服务于「AI 总结」「知识问答」以及将来的 embedding 配置，
 * 挂在任一功能服务上都会让依赖方向变歪。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Presets 返回内置端点预设列表。
 */
export function Presets(): $CancellablePromise<$models.LLMEndpointPreset[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.Presets");
}

/**
 * Probe 对端点做连通性自检。
 * 用协议对应的模型列表端点（通常是 GET /models）而不是发一次真实的 chat 请求：
 * 不消耗 token、不产生费用，且能顺带把可用模型列表带回来给前端做下拉。
 * 若端点不支持列举，只标记为「可达」而非失败。
 * Probe 连通性自检：用用户实际填写的模型发一次最小生成请求。
 * 
 * 语义约定（2026-09 与产品确认）：「测试」的对象是用户填的配置本身——
 * 端点 + 模型 + Key 组合能不能真正出活。早期实现只罗列端点上的模型清单，
 * 用户填的模型压根没被请求过，"自检通过"却实际问答失败，语义是错的。
 * 端点的模型清单仍会附带拉取（辅助排查：填的模型名 vs 端点实际有的），
 * 但判定成败的唯一标准是本次真实请求。
 */
export function Probe(apiKey: string, baseURL: string, protocol: string, model: string): $CancellablePromise<$models.LLMProbeResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.Probe", apiKey, baseURL, protocol, model);
}

/**
 * ProbeEmbedding 对 embedding 端点做连通性自检。
 * 
 * 关键约束：必须探测与实际嵌入请求**完全一致**的地址与协议（normalizeBaseURL + /embeddings），
 * 否则会出现「设置页显示可用、实际建索引却 404」的漂移。这里明确识别 401/403/404 等失败，
 * 而不是让调用方在批量建索引时才报模糊错误。
 */
export function ProbeEmbedding(apiKey: string, baseURL: string, model: string): $CancellablePromise<$models.EmbeddingProbeResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.ProbeEmbedding", apiKey, baseURL, model);
}

/**
 * ProbeRerank 对 rerank 端点做连通性自检。
 * 
 * 关键约束：必须探测与实际重排请求**完全一致**的地址与协议（见 rerankEndpointURL 的注释）。
 * 否则会出现「设置页显示可用、实际 404 被静默降级」的漂移——这正是 P1-3b 的静默失效根因：
 * Ollama 原生不提供 /api/rerank（上游 PR 从未合并），此前该 404 会被降级逻辑静默吞掉，
 * 用户只觉得「开了 rerank 没区别」。这里把它明确识别为「不可用」并给出可操作提示，
 * 与项目「不静默」红线对齐。
 */
export function ProbeRerank(cfg: $models.RerankConfig): $CancellablePromise<$models.RerankProbeResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.LLMConfigService.ProbeRerank", cfg);
}
