// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LLMConfigService 提供端点预设与连通性自检。
 * 独立成一个服务而不是挂在 SummarizeService 上：
 * 自检要同时服务于「AI 总结」「知识问答」以及将来的 embedding 配置，
 * 挂在任一功能服务上都会让依赖方向变歪。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Presets 返回内置端点预设列表。
 * @returns {$CancellablePromise<$models.LLMEndpointPreset[]>}
 */
export function Presets() {
    return $Call.ByID(2377601481).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Probe 对端点做连通性自检。
 * 用 GET /models 而不是发一次真实的 chat 请求：前者不消耗 token、不产生费用，
 * 且能顺带把可用模型列表带回来给前端做下拉。
 * @param {string} apiKey
 * @param {string} baseURL
 * @returns {$CancellablePromise<$models.LLMProbeResult | null>}
 */
export function Probe(apiKey, baseURL) {
    return $Call.ByID(2979814067, apiKey, baseURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ProbeRerank 对 rerank 端点做连通性自检。
 * 
 * 关键约束：必须探测与实际重排请求**完全一致**的地址与协议（见 rerankEndpointURL 的注释）。
 * 否则会出现「设置页显示可用、实际 404 被静默降级」的漂移——这正是 P1-3b 的静默失效根因：
 * Ollama 原生不提供 /api/rerank（上游 PR 从未合并），此前该 404 会被降级逻辑静默吞掉，
 * 用户只觉得「开了 rerank 没区别」。这里把它明确识别为「不可用」并给出可操作提示，
 * 与项目「不静默」红线对齐。
 * @param {$models.RerankConfig} cfg
 * @returns {$CancellablePromise<$models.RerankProbeResult | null>}
 */
export function ProbeRerank(cfg) {
    return $Call.ByID(2112848692, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LLMEndpointPreset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.LLMProbeResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.RerankProbeResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
