// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchivedFile 表示一个归档文件
 * @typedef {Object} ArchivedFile
 * @property {string} path
 * @property {string} name
 * @property {string} originalPath
 * @property {string} archivedAt
 * @property {number} size
 */

/**
 * BaseCell 是表格里的一个单元格。
 * 
 * 同时带 Display 和结构化字段：Display 给前端直接渲染，
 * Kind/List/Num 给前端做类型化渲染（标签做成 chip、数字右对齐、布尔画勾）。
 * @typedef {Object} BaseCell
 * @property {string} property
 * @property {PropKind} kind
 * @property {string} display
 * @property {string[] | null} [list]
 * @property {number} [num]
 * @property {boolean} [bool]
 * @property {boolean} [empty]
 */

/**
 * BaseDef 是一个 .nvbase 文件的完整内容。
 * 
 * 命名没跟 schema.BaseDefinition 一致（那个是 Descriptor 变量名），
 * 避免同名标识符在两个包里指代不同东西。
 * @typedef {Object} BaseDef
 * @property {string} name
 * @property {string} [description]
 * @property {string} [folder] - 限定子目录，空 = 整个工作区
 * @property {BaseFilterGroup} filters
 * @property {BaseView[] | null} views
 */

/**
 * BaseFilter 是一条筛选条件。
 * 
 * Value 用字符串承载而不是 any：这个结构要穿过 JSON 落盘、再穿过 Wails 到前端，
 * any 在这条链路上会退化成 float64/string/bool，类型信息反而更乱。
 * 统一用字符串存原文，比较时按**目标属性的类型**强转 —— 类型的权威来源是数据，不是查询。
 * @typedef {Object} BaseFilter
 * @property {string} property
 * @property {string} operator
 * @property {string} [value]
 * @property {string[] | null} [values] - 仅 in / notIn 使用
 */

/**
 * BaseFilterGroup 是可嵌套的条件组。
 * @typedef {Object} BaseFilterGroup
 * @property {string} conjunction - and（默认）| or
 * @property {BaseFilter[] | null} conditions
 * @property {BaseFilterGroup[] | null} groups
 */

/**
 * BaseGroup 是分组结果的一组。
 * @typedef {Object} BaseGroup
 * @property {string} key
 * @property {string} label
 * @property {number} count
 * @property {(BaseRow | null)[] | null} rows
 */

/**
 * BaseResult 是一次查询的完整输出。
 * @typedef {Object} BaseResult
 * @property {string} viewId
 * @property {string} viewName
 * @property {string} viewType
 * @property {string[] | null} columns
 * @property {(BaseRow | null)[] | null} rows
 * @property {(BaseGroup | null)[] | null} groups
 * @property {number} total
 * @property {number} returned
 * @property {boolean} truncated
 * @property {number} scanned
 * @property {string[] | null} warnings
 */

/**
 * BaseRow 是查询结果的一行（一篇笔记）。
 * @typedef {Object} BaseRow
 * @property {string} path
 * @property {string} title
 * @property {BaseCell[] | null} cells
 */

/**
 * BaseSort 是一条排序规则。
 * @typedef {Object} BaseSort
 * @property {string} property
 * @property {boolean} desc
 */

/**
 * BaseSummary 是视图列表项（不含完整筛选配置，列表页不需要）。
 * @typedef {Object} BaseSummary
 * @property {string} name
 * @property {string} [description]
 * @property {string} [folder]
 * @property {number} viewCount
 * @property {number} filterCount
 * @property {string} updatedAt
 */

/**
 * BaseView 是一个视图配置。
 * @typedef {Object} BaseView
 * @property {string} id
 * @property {string} name
 * @property {string} type - table | board | list
 * @property {string[] | null} columns
 * @property {BaseSort[] | null} sort
 * @property {string} groupBy
 * @property {number} limit - 0 = 用默认上限
 */

/**
 * BuiltinTemplate 描述一个内置模板。
 * @typedef {Object} BuiltinTemplate
 * @property {string} id
 * @property {string} title
 * @property {string} description
 * @property {BaseDef} def
 */

/**
 * CompileAllResult 是 CompileAll 的聚合结果，专为 Wails 绑定设计：
 * 返回单一结构体 + error（而非 Go 惯用的 (results, []error) 双返回值）。
 * 原因：Wails 会把多返回值序列化为元组，而 []error 是接口切片，
 * 每个 error 经 JSON 会退化成 {}，前端拿不到任何错误信息。
 * 这里用结构化的 CompileErrorItem 承载「路径 + 消息」，前端可逐条展示。
 * @typedef {Object} CompileAllResult
 * @property {(CompileResult | null)[] | null} Results - Results 编译成功的篇目。
 * @property {CompileErrorItem[] | null} Errors - Errors 单篇失败明细（路径 + 原因），不阻断其他篇。
 */

/**
 * CompileErrorItem 单篇编译失败的路径与原因。
 * @typedef {Object} CompileErrorItem
 * @property {string} Path - Path 失败的 Inbox 相对路径。
 * @property {string} Error - Error 人类可读的错误原因。
 */

/**
 * CompileOutput 是「知识编译」的结构化产出。
 * @typedef {Object} CompileOutput
 * @property {string} TLDR - TLDR 一句话摘要，调用方约束模型控制在 200 字以内。
 * @property {string[] | null} Tags - Tags AI 建议的标签（已去重，不含前导 #）。
 * @property {string[] | null} SuggestedLinks - SuggestedLinks AI 建议的双链目标，形如 "笔记标题"（不含 [[ ]]）。
 */

/**
 * CompileResult 单篇笔记的编译结果。
 * @typedef {Object} CompileResult
 * @property {string} Source - Source 原始（Inbox 内）相对路径。
 * @property {string} Dest - Dest 编译后（Compiled 内）相对路径。
 * @property {string} SnapshotID - SnapshotID 编译前建立的快照 ID，用于整体撤销。
 * @property {CompileOutput | null} Output - Output AI 产出的结构化内容。
 */

/**
 * DiffOp 表示 diff 中的一行操作
 * @typedef {Object} DiffOp
 * @property {string} type
 * @property {number} oldLine - 1-based；insert 时为 0
 * @property {number} newLine - 1-based；delete 时为 0
 * @property {string} text
 * @property {number} [count] - 仅 DiffGap 使用：折叠的行数
 */

/**
 * FileNode 表示文件树中的一个节点（文件或文件夹）
 * @typedef {Object} FileNode
 * @property {string} name
 * @property {string} path - 相对于工作区根目录的路径
 * @property {string} fullPath - 绝对路径
 * @property {boolean} isDir
 * @property {(FileNode | null)[] | null} [children]
 * @property {number} [size]
 * @property {string} [modTime]
 */

/**
 * GitStatus 是工作区的 Git 概况，供前端决定展示「初始化」还是「提交」。
 * @typedef {Object} GitStatus
 * @property {boolean} installed - 系统里是否有可用的 git
 * @property {boolean} isRepo - 工作区是否已是 git 仓库
 * @property {string} branch - 当前分支（非仓库时为空）
 * @property {number} changed - 已跟踪文件的变更数（含暂存）
 * @property {number} untracked - 未跟踪文件数
 */

/**
 * GraphData 知识图谱数据
 * @typedef {Object} GraphData
 * @property {(GraphNode | null)[] | null} nodes
 * @property {(GraphEdge | null)[] | null} edges
 */

/**
 * GraphEdge 表示一条双向链接
 * @typedef {Object} GraphEdge
 * @property {string} source - 源节点 ID
 * @property {string} target - 目标节点 ID
 */

/**
 * GraphNode 表示知识图谱中的一个笔记节点
 * @typedef {Object} GraphNode
 * @property {string} id - 相对路径，作为唯一标识
 * @property {string} title - 笔记标题（文件名或首个 # 标题）
 * @property {string} path - 相对路径（未解析节点为 "unresolved:名称"）
 * @property {number} degree - 连接数，用于节点大小
 * @property {boolean} resolved - 是否为已存在的笔记（false 表示未解析的虚拟节点）
 */

/**
 * ImportOptions 导入选项
 * @typedef {Object} ImportOptions
 * @property {string} conflictStrategy - ConflictStrategy 冲突策略：skip=跳过 / rename=自动重命名 / overwrite=覆盖（默认 skip）
 * @property {boolean} includeSubdirs - IncludeSubdirs 是否保留源目录的子目录结构（默认 true）
 */

/**
 * ImportResult 导入结果统计
 * @typedef {Object} ImportResult
 * @property {number} imported - 成功导入文件数
 * @property {number} skipped - 跳过文件数（冲突/非 md）
 * @property {number} renamed - 冲突自动重命名数
 * @property {string[] | null} errors - 失败明细（不中断整体导入）
 */

/**
 * LLMEndpointPreset 描述一个可一键填入的端点预设。
 * @typedef {Object} LLMEndpointPreset
 * @property {string} id
 * @property {string} label
 * @property {string} baseURL
 * @property {string} model
 * @property {boolean} requiresKey
 * @property {string} hint
 */

/**
 * LLMProbeResult 连通性自检结果。
 * @typedef {Object} LLMProbeResult
 * @property {boolean} ok
 * @property {string} endpoint - 实际探测的地址
 * @property {boolean} isLocal - 是否判定为本机端点（免鉴权）
 * @property {string[] | null} models - 端点声明可用的模型（拉取失败则为空）
 * @property {number} latencyMs - 往返耗时
 * @property {string} message - 失败原因或补充说明
 */

/**
 * LinkCandidate 是编辑器 [[ 自动补全的候选项。
 * @typedef {Object} LinkCandidate
 * @property {string} kind - "file" | "heading"
 * @property {string} file - 相对路径，如 "Notes/foo.md"
 * @property {string} fileBase - 无扩展名文件名，如 "foo"
 * @property {string} heading - heading 类型时为目标标题；file 类型为空
 * @property {string} display - 人类可读标签（下拉里展示）
 */

/**
 * PropKind 是属性值的推断类型。
 * 
 * 为什么必须带类型：Bases 的筛选与排序要按语义比较，不能一律当字符串。
 * 字符串比较下 "10" < "9"、"2026-01-02" 与 "2026-1-2" 不等价、
 * true 和 "true" 无法区分——这些在「按 rating 排序」「筛 published=true」
 * 这类真实用法里全是错的结果。
 * @readonly
 * @enum {string}
 */
export const PropKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindString 普通文本
     */
    KindString: "string",

    /**
     * KindNumber 整数或浮点
     */
    KindNumber: "number",

    /**
     * KindBool true / false / yes / no
     */
    KindBool: "bool",

    /**
     * KindDate 日期或日期时间
     */
    KindDate: "date",

    /**
     * KindList 数组（内联 [a, b] 或块式 - a）
     */
    KindList: "list",
};

/**
 * PropertyMeta 描述工作区里一个属性的统计信息，供前端属性选择器使用。
 * @typedef {Object} PropertyMeta
 * @property {string} name
 * @property {PropKind} kind - 出现最多的类型
 * @property {number} count - 有该属性的笔记数
 * @property {boolean} implicit - 是否为 file.* / todo.* 隐式属性
 * @property {string[] | null} samples - 最多 8 个样例值，便于填筛选条件
 */

/**
 * QnACitation 表示回答中引用的一处知识库内容
 * @typedef {Object} QnACitation
 * @property {number} index - 引用编号（从 1 开始，与回答中的 [n] 对应）
 * @property {string} path - 文档相对路径
 * @property {string} title - 文档标题
 * @property {string} snippet - 命中片段摘要
 * @property {string} heading - 以下两项是 P0-2 分块检索的产物，让引用能定位到具体章节而不是整篇。 前端暂未使用，属于向前兼容地扩展（不读不影响既有行为）。 该块所属的最近上级标题
 * @property {number} chunkIndex - 块在文档内的序号，从 0 开始
 */

/**
 * QnAResponse 是一次问答的完整结果
 * @typedef {Object} QnAResponse
 * @property {string} answer - Markdown 格式的回答
 * @property {QnACitation[] | null} citations - 引用的文档列表
 */

/**
 * Reminder 表示一个提醒
 * @typedef {Object} Reminder
 * @property {string} id
 * @property {string} filePath
 * @property {string} fileName
 * @property {string} content
 * @property {string} remindAt - ISO 8601 格式
 * @property {string} createdAt
 * @property {boolean} completed
 */

/**
 * RerankConfig 是 rerank 端点的连接配置（与 embedding / LLM 配置相互独立）。
 * @typedef {Object} RerankConfig
 * @property {RerankProvider} provider
 * @property {string} baseURL
 * @property {string} model
 * @property {string} apiKey
 */

/**
 * RerankProvider 标识重排序服务的厂商/协议。
 * @readonly
 * @enum {string}
 */
export const RerankProvider = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * RerankProviderOllama 本机 Ollama /api/rerank 端点（默认，免鉴权）。
     */
    RerankProviderOllama: "ollama",

    /**
     * RerankProviderCohere Cohere /v1/rerank 端点（需 API Key）。
     */
    RerankProviderCohere: "cohere",
};

/**
 * SearchIndexStats 描述索引的覆盖情况，供状态栏提示（P0-5）
 * @typedef {Object} SearchIndexStats
 * @property {number} docCount - 已索引文档数
 * @property {number} tokenCount - 倒排表 token 数
 * @property {boolean} scanComplete - false = 触及 maxScanFiles 上限，仍有文件未扫
 * @property {number} skippedCount - 因体积超过 maxSearchFileSize 被跳过的文件数
 */

/**
 * SearchResult 表示一个搜索结果
 * @typedef {Object} SearchResult
 * @property {string} path
 * @property {string} title
 * @property {string} snippet
 * @property {number} matchCount
 * @property {string} modTime - P0-4：供前端「按最近修改」排序
 */

/**
 * Snapshot 表示一份历史版本的元数据（内容存在 objects 里，按 Hash 寻址）
 * @typedef {Object} Snapshot
 * @property {string} id
 * @property {string} path - 相对工作区路径，统一用 / 分隔
 * @property {string} hash - 内容 sha256（内容寻址键）
 * @property {number} size - 原始内容字节数（非压缩后）
 * @property {string} createdAt
 * @property {string} reason
 */

/**
 * SnapshotDiff 是某个快照与目标版本（另一快照或当前文件）的差异
 * @typedef {Object} SnapshotDiff
 * @property {string} path
 * @property {string} fromId
 * @property {string} toId - 空串表示「当前工作区文件」
 * @property {string} fromAt
 * @property {string} toAt
 * @property {DiffOp[] | null} ops
 * @property {number} added
 * @property {number} removed
 * @property {boolean} truncated
 * @property {boolean} identical
 */

/**
 * SnapshotFileSummary 按文件聚合的快照概览，用于时间机器面板左侧文件列表
 * @typedef {Object} SnapshotFileSummary
 * @property {string} path
 * @property {number} count
 * @property {string} latestAt
 * @property {number} bytes
 */

/**
 * SnapshotRestoreResult 恢复结果。BackupID 是恢复前自动打的安全备份，
 * 让「恢复错了」也能再退回去——AI/批量改写场景下这一步是刚需。
 * @typedef {Object} SnapshotRestoreResult
 * @property {string} path
 * @property {string} restoredId
 * @property {string} backupId
 * @property {number} bytes
 */

/**
 * SnapshotStats 历史库占用概览
 * @typedef {Object} SnapshotStats
 * @property {number} snapshots
 * @property {number} files
 * @property {number} objects
 * @property {number} diskBytes
 */

/**
 * TagFileInfo 表示包含某个标签的文件信息
 * @typedef {Object} TagFileInfo
 * @property {string} path
 * @property {string} title
 */

/**
 * TagInfo 表示一个标签及其使用次数
 * @typedef {Object} TagInfo
 * @property {string} name
 * @property {number} count
 */

/**
 * TaskInfo 是任务的对外快照（会被 Wails 序列化成前端 TS 类型）。
 * @typedef {Object} TaskInfo
 * @property {string} id
 * @property {string} name
 * @property {TaskStatus} status
 * @property {number} done
 * @property {number} total
 * @property {number} percent
 * @property {string} message
 * @property {string} [error]
 * @property {string} startedAt
 * @property {string} [endedAt]
 */

/**
 * TaskStatus 任务状态
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 已提交，等待并发名额
     */
    TaskPending: "pending",

    /**
     * 正在执行
     */
    TaskRunning: "running",

    /**
     * 正常完成
     */
    TaskSucceeded: "succeeded",

    /**
     * 返回错误
     */
    TaskFailed: "failed",

    /**
     * 被用户取消
     */
    TaskCancelled: "cancelled",
};

/**
 * TemplateInfo 描述一个可用模板。
 * @typedef {Object} TemplateInfo
 * @property {string} name - 模板名（文件名去扩展名），即模板 ID
 * @property {string[] | null} variables - 需要用户填写的自定义变量（已排除内置）
 */

/**
 * TodoItem 表示一个待办事项
 * @typedef {Object} TodoItem
 * @property {string} id
 * @property {string} filePath
 * @property {string} fileName
 * @property {string} content
 * @property {number} lineIndex
 * @property {boolean} completed
 * @property {string} priority - high, medium, low
 */

/**
 * TrashedFile 表示回收站中的文件
 * @typedef {Object} TrashedFile
 * @property {string} id
 * @property {string} path
 * @property {string} name
 * @property {string} originalPath
 * @property {string} deletedAt
 * @property {number} size
 */

/**
 * Workspace 表示一个知识库工作区
 * @typedef {Object} Workspace
 * @property {string} id
 * @property {string} name
 * @property {string} path
 * @property {string} createdAt
 * @property {string} lastOpenedAt
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
