// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchivedFile 表示一个归档文件
 */
export interface ArchivedFile {
    "path": string;
    "name": string;
    "originalPath": string;
    "archivedAt": string;
    "size": number;
}

/**
 * BaseCell 是表格里的一个单元格。
 * 
 * 同时带 Display 和结构化字段：Display 给前端直接渲染，
 * Kind/List/Num 给前端做类型化渲染（标签做成 chip、数字右对齐、布尔画勾）。
 */
export interface BaseCell {
    "property": string;
    "kind": PropKind;
    "display": string;
    "list"?: string[] | null;
    "num"?: number;
    "bool"?: boolean;
    "empty"?: boolean;
}

/**
 * BaseDef 是一个 .nvbase 文件的完整内容。
 * 
 * 命名没跟 schema.BaseDefinition 一致（那个是 Descriptor 变量名），
 * 避免同名标识符在两个包里指代不同东西。
 */
export interface BaseDef {
    "name": string;
    "description"?: string;

    /**
     * 限定子目录，空 = 整个工作区
     */
    "folder"?: string;
    "filters": BaseFilterGroup;
    "views": BaseView[] | null;
}

/**
 * BaseFilter 是一条筛选条件。
 * 
 * Value 用字符串承载而不是 any：这个结构要穿过 JSON 落盘、再穿过 Wails 到前端，
 * any 在这条链路上会退化成 float64/string/bool，类型信息反而更乱。
 * 统一用字符串存原文，比较时按**目标属性的类型**强转 —— 类型的权威来源是数据，不是查询。
 */
export interface BaseFilter {
    "property": string;
    "operator": string;
    "value"?: string;

    /**
     * 仅 in / notIn 使用
     */
    "values"?: string[] | null;
}

/**
 * BaseFilterGroup 是可嵌套的条件组。
 */
export interface BaseFilterGroup {
    /**
     * and（默认）| or
     */
    "conjunction": string;
    "conditions": BaseFilter[] | null;
    "groups": BaseFilterGroup[] | null;
}

/**
 * BaseGroup 是分组结果的一组。
 */
export interface BaseGroup {
    "key": string;
    "label": string;
    "count": number;
    "rows": (BaseRow | null)[] | null;
}

/**
 * BaseResult 是一次查询的完整输出。
 */
export interface BaseResult {
    "viewId": string;
    "viewName": string;
    "viewType": string;
    "columns": string[] | null;
    "rows": (BaseRow | null)[] | null;
    "groups": (BaseGroup | null)[] | null;
    "total": number;
    "returned": number;
    "truncated": boolean;
    "scanned": number;
    "warnings": string[] | null;
}

/**
 * BaseRow 是查询结果的一行（一篇笔记）。
 */
export interface BaseRow {
    "path": string;
    "title": string;
    "cells": BaseCell[] | null;
}

/**
 * BaseSort 是一条排序规则。
 */
export interface BaseSort {
    "property": string;
    "desc": boolean;
}

/**
 * BaseSummary 是视图列表项（不含完整筛选配置，列表页不需要）。
 */
export interface BaseSummary {
    "name": string;
    "description"?: string;
    "folder"?: string;
    "viewCount": number;
    "filterCount": number;
    "updatedAt": string;
}

/**
 * BaseView 是一个视图配置。
 */
export interface BaseView {
    "id": string;
    "name": string;

    /**
     * table | board | list
     */
    "type": string;
    "columns": string[] | null;
    "sort": BaseSort[] | null;
    "groupBy": string;

    /**
     * 0 = 用默认上限
     */
    "limit": number;
}

/**
 * BuiltinTemplate 描述一个内置模板。
 */
export interface BuiltinTemplate {
    "id": string;
    "title": string;
    "description": string;
    "def": BaseDef;
}

/**
 * CompileAllResult 是 CompileAll 的聚合结果，专为 Wails 绑定设计：
 * 返回单一结构体 + error（而非 Go 惯用的 (results, []error) 双返回值）。
 * 原因：Wails 会把多返回值序列化为元组，而 []error 是接口切片，
 * 每个 error 经 JSON 会退化成 {}，前端拿不到任何错误信息。
 * 这里用结构化的 CompileErrorItem 承载「路径 + 消息」，前端可逐条展示。
 */
export interface CompileAllResult {
    /**
     * Results 编译成功的篇目。
     */
    "Results": (CompileResult | null)[] | null;

    /**
     * Errors 单篇失败明细（路径 + 原因），不阻断其他篇。
     */
    "Errors": CompileErrorItem[] | null;
}

/**
 * CompileErrorItem 单篇编译失败的路径与原因。
 */
export interface CompileErrorItem {
    /**
     * Path 失败的 Inbox 相对路径。
     */
    "Path": string;

    /**
     * Error 人类可读的错误原因。
     */
    "Error": string;
}

/**
 * CompileOutput 是「知识编译」的结构化产出。
 */
export interface CompileOutput {
    /**
     * TLDR 一句话摘要，调用方约束模型控制在 200 字以内。
     */
    "TLDR": string;

    /**
     * Tags AI 建议的标签（已去重，不含前导 #）。
     */
    "Tags": string[] | null;

    /**
     * SuggestedLinks AI 建议的双链目标，形如 "笔记标题"（不含 [[ ]]）。
     */
    "SuggestedLinks": string[] | null;
}

/**
 * CompileResult 单篇笔记的编译结果。
 */
export interface CompileResult {
    /**
     * Source 原始（Inbox 内）相对路径。
     */
    "Source": string;

    /**
     * Dest 编译后（Compiled 内）相对路径。
     */
    "Dest": string;

    /**
     * SnapshotID 编译前建立的快照 ID，用于整体撤销。
     */
    "SnapshotID": string;

    /**
     * Output AI 产出的结构化内容。
     */
    "Output": CompileOutput | null;
}

/**
 * DiffOp 表示 diff 中的一行操作
 */
export interface DiffOp {
    "type": string;

    /**
     * 1-based；insert 时为 0
     */
    "oldLine": number;

    /**
     * 1-based；delete 时为 0
     */
    "newLine": number;
    "text": string;

    /**
     * 仅 DiffGap 使用：折叠的行数
     */
    "count"?: number;
}

/**
 * EmbeddingProbeResult 嵌入端点连通性自检结果（镜像 RerankProbeResult / LLMProbeResult）。
 * 供前端「设置 → 语义检索」页的「测试连接」按钮使用，让 embedding 配置在保存前
 * 就被明确校验——避免「以为配好、实际建向量索引才 404」的等待浪费，与「不静默」红线对齐。
 */
export interface EmbeddingProbeResult {
    "ok": boolean;

    /**
     * 实际探测的地址（应与真实嵌入请求一致）
     */
    "endpoint": string;

    /**
     * 是否本机端点（免鉴权）
     */
    "isLocal": boolean;

    /**
     * 往返耗时
     */
    "latencyMs": number;

    /**
     * 失败原因或可操作提示
     */
    "message": string;
}

/**
 * FileNode 表示文件树中的一个节点（文件或文件夹）
 */
export interface FileNode {
    "name": string;

    /**
     * 相对于工作区根目录的路径
     */
    "path": string;

    /**
     * 绝对路径
     */
    "fullPath": string;
    "isDir": boolean;
    "children"?: (FileNode | null)[] | null;
    "size"?: number;
    "modTime"?: string;
}

/**
 * GitStatus 是工作区的 Git 概况，供前端决定展示「初始化」还是「提交」。
 */
export interface GitStatus {
    /**
     * 系统里是否有可用的 git
     */
    "installed": boolean;

    /**
     * 工作区是否已是 git 仓库
     */
    "isRepo": boolean;

    /**
     * 当前分支（非仓库时为空）
     */
    "branch": string;

    /**
     * 已跟踪文件的变更数（含暂存）
     */
    "changed": number;

    /**
     * 未跟踪文件数
     */
    "untracked": number;
}

/**
 * GraphData 知识图谱数据
 */
export interface GraphData {
    "nodes": (GraphNode | null)[] | null;
    "edges": (GraphEdge | null)[] | null;
}

/**
 * GraphEdge 表示一条双向链接
 */
export interface GraphEdge {
    /**
     * 源节点 ID
     */
    "source": string;

    /**
     * 目标节点 ID
     */
    "target": string;
}

/**
 * GraphNode 表示知识图谱中的一个笔记节点
 */
export interface GraphNode {
    /**
     * 相对路径，作为唯一标识
     */
    "id": string;

    /**
     * 笔记标题（文件名或首个 # 标题）
     */
    "title": string;

    /**
     * 相对路径（未解析节点为 "unresolved:名称"）
     */
    "path": string;

    /**
     * 连接数，用于节点大小
     */
    "degree": number;

    /**
     * 是否为已存在的笔记（false 表示未解析的虚拟节点）
     */
    "resolved": boolean;
}

/**
 * ImportOptions 导入选项
 */
export interface ImportOptions {
    /**
     * ConflictStrategy 冲突策略：skip=跳过 / rename=自动重命名 / overwrite=覆盖（默认 skip）
     */
    "conflictStrategy": string;

    /**
     * IncludeSubdirs 是否保留源目录的子目录结构（默认 true）
     */
    "includeSubdirs": boolean;
}

/**
 * ImportResult 导入结果统计
 */
export interface ImportResult {
    /**
     * 成功导入文件数
     */
    "imported": number;

    /**
     * 跳过文件数（冲突/非 md）
     */
    "skipped": number;

    /**
     * 冲突自动重命名数
     */
    "renamed": number;

    /**
     * 失败明细（不中断整体导入）
     */
    "errors": string[] | null;
}

/**
 * LLMEndpointPreset 描述一个可一键填入的端点预设。
 */
export interface LLMEndpointPreset {
    "id": string;
    "label": string;
    "baseURL": string;
    "model": string;
    "requiresKey": boolean;
    "hint": string;
}

/**
 * LLMProbeResult 连通性自检结果。
 */
export interface LLMProbeResult {
    "ok": boolean;

    /**
     * 实际探测的地址
     */
    "endpoint": string;

    /**
     * 是否判定为本机端点（免鉴权）
     */
    "isLocal": boolean;

    /**
     * 端点声明可用的模型（拉取失败则为空）
     */
    "models": string[] | null;

    /**
     * 往返耗时
     */
    "latencyMs": number;

    /**
     * 失败原因或补充说明
     */
    "message": string;
}

/**
 * LinkCandidate 是编辑器 [[ 自动补全的候选项。
 */
export interface LinkCandidate {
    /**
     * "file" | "heading"
     */
    "kind": string;

    /**
     * 相对路径，如 "Notes/foo.md"
     */
    "file": string;

    /**
     * 无扩展名文件名，如 "foo"
     */
    "fileBase": string;

    /**
     * heading 类型时为目标标题；file 类型为空
     */
    "heading": string;

    /**
     * 人类可读标签（下拉里展示）
     */
    "display": string;
}

/**
 * PropKind 是属性值的推断类型。
 * 
 * 为什么必须带类型：Bases 的筛选与排序要按语义比较，不能一律当字符串。
 * 字符串比较下 "10" < "9"、"2026-01-02" 与 "2026-1-2" 不等价、
 * true 和 "true" 无法区分——这些在「按 rating 排序」「筛 published=true」
 * 这类真实用法里全是错的结果。
 */
export enum PropKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindString 普通文本
     */
    KindString = "string",

    /**
     * KindNumber 整数或浮点
     */
    KindNumber = "number",

    /**
     * KindBool true / false / yes / no
     */
    KindBool = "bool",

    /**
     * KindDate 日期或日期时间
     */
    KindDate = "date",

    /**
     * KindList 数组（内联 [a, b] 或块式 - a）
     */
    KindList = "list",
};

/**
 * PropertyMeta 描述工作区里一个属性的统计信息，供前端属性选择器使用。
 */
export interface PropertyMeta {
    "name": string;

    /**
     * 出现最多的类型
     */
    "kind": PropKind;

    /**
     * 有该属性的笔记数
     */
    "count": number;

    /**
     * 是否为 file.* / todo.* 隐式属性
     */
    "implicit": boolean;

    /**
     * 最多 8 个样例值，便于填筛选条件
     */
    "samples": string[] | null;
}

/**
 * QnACitation 表示回答中引用的一处知识库内容
 */
export interface QnACitation {
    /**
     * 引用编号（从 1 开始，与回答中的 [n] 对应）
     */
    "index": number;

    /**
     * 文档相对路径
     */
    "path": string;

    /**
     * 文档标题
     */
    "title": string;

    /**
     * 命中片段摘要
     */
    "snippet": string;

    /**
     * 以下两项是 P0-2 分块检索的产物，让引用能定位到具体章节而不是整篇。
     * 前端暂未使用，属于向前兼容地扩展（不读不影响既有行为）。
     * 该块所属的最近上级标题
     */
    "heading": string;

    /**
     * 块在文档内的序号，从 0 开始
     */
    "chunkIndex": number;
}

/**
 * QnAResponse 是一次问答的完整结果
 */
export interface QnAResponse {
    /**
     * Markdown 格式的回答
     */
    "answer": string;

    /**
     * 引用的文档列表
     */
    "citations": QnACitation[] | null;
}

/**
 * Reminder 表示一个提醒
 */
export interface Reminder {
    "id": string;
    "filePath": string;
    "fileName": string;
    "content": string;

    /**
     * ISO 8601 格式
     */
    "remindAt": string;
    "createdAt": string;
    "completed": boolean;
}

/**
 * RerankConfig 是 rerank 端点的连接配置（与 embedding / LLM 配置相互独立）。
 */
export interface RerankConfig {
    "provider": RerankProvider;
    "baseURL": string;
    "model": string;
    "apiKey": string;
}

/**
 * RerankProbeResult 重排端点连通性自检结果（镜像 LLMProbeResult）。
 * 供前端「设置 → 重排序」页的「测试连接」按钮使用，让 rerank 配置在保存前
 * 就被明确校验——避免 P1-3b 的静默失效（Ollama 无 /api/rerank，404 被降级逻辑吞掉）。
 */
export interface RerankProbeResult {
    "ok": boolean;

    /**
     * 实际探测的地址（应与真实重排请求一致）
     */
    "endpoint": string;

    /**
     * 是否本机端点（免鉴权）
     */
    "isLocal": boolean;

    /**
     * 往返耗时
     */
    "latencyMs": number;

    /**
     * 失败原因或可操作提示
     */
    "message": string;
}

/**
 * RerankProvider 标识重排序服务的厂商/协议。
 * Ollama 已从选项中移除（原生不支持 /api/rerank，上游 PR 未合并）。
 */
export enum RerankProvider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * RerankProviderCohere Cohere / 硅基流动等兼容 /v1/rerank 端点（需 API Key）。
     */
    RerankProviderCohere = "cohere",
};

/**
 * SearchIndexStats 描述索引的覆盖情况，供状态栏提示（P0-5）
 */
export interface SearchIndexStats {
    /**
     * 已索引文档数
     */
    "docCount": number;

    /**
     * 倒排表 token 数
     */
    "tokenCount": number;

    /**
     * false = 触及 maxScanFiles 上限，仍有文件未扫
     */
    "scanComplete": boolean;

    /**
     * 因体积超过 maxSearchFileSize 被跳过的文件数
     */
    "skippedCount": number;
}

/**
 * SearchResult 表示一个搜索结果
 */
export interface SearchResult {
    "path": string;
    "title": string;
    "snippet": string;
    "matchCount": number;

    /**
     * P0-4：供前端「按最近修改」排序
     */
    "modTime": string;
}

/**
 * Snapshot 表示一份历史版本的元数据（内容存在 objects 里，按 Hash 寻址）
 */
export interface Snapshot {
    "id": string;

    /**
     * 相对工作区路径，统一用 / 分隔
     */
    "path": string;

    /**
     * 内容 sha256（内容寻址键）
     */
    "hash": string;

    /**
     * 原始内容字节数（非压缩后）
     */
    "size": number;
    "createdAt": string;
    "reason": string;
}

/**
 * SnapshotDiff 是某个快照与目标版本（另一快照或当前文件）的差异
 */
export interface SnapshotDiff {
    "path": string;
    "fromId": string;

    /**
     * 空串表示「当前工作区文件」
     */
    "toId": string;
    "fromAt": string;
    "toAt": string;
    "ops": DiffOp[] | null;
    "added": number;
    "removed": number;
    "truncated": boolean;
    "identical": boolean;
}

/**
 * SnapshotFileSummary 按文件聚合的快照概览，用于时间机器面板左侧文件列表
 */
export interface SnapshotFileSummary {
    "path": string;
    "count": number;
    "latestAt": string;
    "bytes": number;
}

/**
 * SnapshotRestoreResult 恢复结果。BackupID 是恢复前自动打的安全备份，
 * 让「恢复错了」也能再退回去——AI/批量改写场景下这一步是刚需。
 */
export interface SnapshotRestoreResult {
    "path": string;
    "restoredId": string;
    "backupId": string;
    "bytes": number;
}

/**
 * SnapshotStats 历史库占用概览
 */
export interface SnapshotStats {
    "snapshots": number;
    "files": number;
    "objects": number;
    "diskBytes": number;
}

/**
 * TagFileInfo 表示包含某个标签的文件信息
 */
export interface TagFileInfo {
    "path": string;
    "title": string;
}

/**
 * TagInfo 表示一个标签及其使用次数
 */
export interface TagInfo {
    "name": string;
    "count": number;
}

/**
 * TaskInfo 是任务的对外快照（会被 Wails 序列化成前端 TS 类型）。
 */
export interface TaskInfo {
    "id": string;
    "name": string;
    "status": TaskStatus;
    "done": number;
    "total": number;
    "percent": number;
    "message": string;
    "error"?: string;
    "startedAt": string;
    "endedAt"?: string;
}

/**
 * TaskStatus 任务状态
 */
export enum TaskStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 已提交，等待并发名额
     */
    TaskPending = "pending",

    /**
     * 正在执行
     */
    TaskRunning = "running",

    /**
     * 正常完成
     */
    TaskSucceeded = "succeeded",

    /**
     * 返回错误
     */
    TaskFailed = "failed",

    /**
     * 被用户取消
     */
    TaskCancelled = "cancelled",
};

/**
 * TemplateInfo 描述一个可用模板。
 */
export interface TemplateInfo {
    /**
     * 模板名（文件名去扩展名），即模板 ID
     */
    "name": string;

    /**
     * 需要用户填写的自定义变量（已排除内置）
     */
    "variables": string[] | null;
}

/**
 * TodayStats 今日工作台统计。
 * 所有数字都从工作区文件与既有索引派生，用户不需要为仪表盘维护任何数据。
 */
export interface TodayStats {
    /**
     * 今天有改动的 .md 笔记数
     */
    "editedToday": number;

    /**
     * 连续有笔记改动的天数（今天没写则从昨天回溯）
     */
    "streakDays": number;

    /**
     * 未完成待办总数
     */
    "pendingTodos": number;

    /**
     * 未完成中带 !! 的高优先级数量
     */
    "highPriorityTodos": number;

    /**
     * 已到期未完成的提醒数
     */
    "dueReminders": number;

    /**
     * 最近改动的笔记相对路径（正斜杠，最多 5 篇）
     */
    "recentFiles": string[] | null;
}

/**
 * TodoItem 表示一个待办事项
 */
export interface TodoItem {
    "id": string;
    "filePath": string;
    "fileName": string;
    "content": string;
    "lineIndex": number;
    "completed": boolean;

    /**
     * high, medium, low
     */
    "priority": string;
}

/**
 * TrashedFile 表示回收站中的文件
 */
export interface TrashedFile {
    "id": string;
    "path": string;
    "name": string;
    "originalPath": string;
    "deletedAt": string;
    "size": number;
}

/**
 * Workspace 表示一个知识库工作区
 */
export interface Workspace {
    "id": string;
    "name": string;
    "path": string;
    "createdAt": string;
    "lastOpenedAt": string;
}
