// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArchivedFile 表示一个归档文件
 */
export interface ArchivedFile {
    "path": string;
    "name": string;
    "originalPath": string;
    "archivedAt": string;
    "size": number;
}

/**
 * FileNode 表示文件树中的一个节点（文件或文件夹）
 */
export interface FileNode {
    "name": string;

    /**
     * 相对于工作区根目录的路径
     */
    "path": string;

    /**
     * 绝对路径
     */
    "fullPath": string;
    "isDir": boolean;
    "children"?: (FileNode | null)[] | null;
    "size"?: number;
    "modTime"?: string;
}

/**
 * GraphData 知识图谱数据
 */
export interface GraphData {
    "nodes": (GraphNode | null)[] | null;
    "edges": (GraphEdge | null)[] | null;
}

/**
 * GraphEdge 表示一条双向链接
 */
export interface GraphEdge {
    /**
     * 源节点 ID
     */
    "source": string;

    /**
     * 目标节点 ID
     */
    "target": string;
}

/**
 * GraphNode 表示知识图谱中的一个笔记节点
 */
export interface GraphNode {
    /**
     * 相对路径，作为唯一标识
     */
    "id": string;

    /**
     * 笔记标题（文件名或首个 # 标题）
     */
    "title": string;

    /**
     * 相对路径（未解析节点为 "unresolved:名称"）
     */
    "path": string;

    /**
     * 连接数，用于节点大小
     */
    "degree": number;

    /**
     * 是否为已存在的笔记（false 表示未解析的虚拟节点）
     */
    "resolved": boolean;
}

/**
 * ImportOptions 导入选项
 */
export interface ImportOptions {
    /**
     * ConflictStrategy 冲突策略：skip=跳过 / rename=自动重命名 / overwrite=覆盖（默认 skip）
     */
    "conflictStrategy": string;

    /**
     * IncludeSubdirs 是否保留源目录的子目录结构（默认 true）
     */
    "includeSubdirs": boolean;
}

/**
 * ImportResult 导入结果统计
 */
export interface ImportResult {
    /**
     * 成功导入文件数
     */
    "imported": number;

    /**
     * 跳过文件数（冲突/非 md）
     */
    "skipped": number;

    /**
     * 冲突自动重命名数
     */
    "renamed": number;

    /**
     * 失败明细（不中断整体导入）
     */
    "errors": string[] | null;
}

/**
 * QnACitation 表示回答中引用的一篇知识库文档
 */
export interface QnACitation {
    /**
     * 引用编号（从 1 开始，与回答中的 [n] 对应）
     */
    "index": number;

    /**
     * 文档相对路径
     */
    "path": string;

    /**
     * 文档标题
     */
    "title": string;

    /**
     * 命中片段摘要
     */
    "snippet": string;
}

/**
 * QnAResponse 是一次问答的完整结果
 */
export interface QnAResponse {
    /**
     * Markdown 格式的回答
     */
    "answer": string;

    /**
     * 引用的文档列表
     */
    "citations": QnACitation[] | null;
}

/**
 * Reminder 表示一个提醒
 */
export interface Reminder {
    "id": string;
    "filePath": string;
    "fileName": string;
    "content": string;

    /**
     * ISO 8601 格式
     */
    "remindAt": string;
    "createdAt": string;
    "completed": boolean;
}

/**
 * SearchResult 表示一个搜索结果
 */
export interface SearchResult {
    "path": string;
    "title": string;
    "snippet": string;
    "matchCount": number;
}

/**
 * TagFileInfo 表示包含某个标签的文件信息
 */
export interface TagFileInfo {
    "path": string;
    "title": string;
}

/**
 * TagInfo 表示一个标签及其使用次数
 */
export interface TagInfo {
    "name": string;
    "count": number;
}

/**
 * TodoItem 表示一个待办事项
 */
export interface TodoItem {
    "id": string;
    "filePath": string;
    "fileName": string;
    "content": string;
    "lineIndex": number;
    "completed": boolean;

    /**
     * high, medium, low
     */
    "priority": string;
}

/**
 * TrashedFile 表示回收站中的文件
 */
export interface TrashedFile {
    "id": string;
    "path": string;
    "name": string;
    "originalPath": string;
    "deletedAt": string;
    "size": number;
}

/**
 * Workspace 表示一个知识库工作区
 */
export interface Workspace {
    "id": string;
    "name": string;
    "path": string;
    "createdAt": string;
    "lastOpenedAt": string;
}
