// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ArchivedFile 表示一个归档文件
 */
export class ArchivedFile {
    /**
     * Creates a new ArchivedFile instance.
     * @param {Partial<ArchivedFile>} [$$source = {}] - The source object to create the ArchivedFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("originalPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalPath"] = "";
        }
        if (!("archivedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivedAt"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchivedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchivedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchivedFile(/** @type {Partial<ArchivedFile>} */($$parsedSource));
    }
}

/**
 * BaseCell 是表格里的一个单元格。
 * 
 * 同时带 Display 和结构化字段：Display 给前端直接渲染，
 * Kind/List/Num 给前端做类型化渲染（标签做成 chip、数字右对齐、布尔画勾）。
 */
export class BaseCell {
    /**
     * Creates a new BaseCell instance.
     * @param {Partial<BaseCell>} [$$source = {}] - The source object to create the BaseCell.
     */
    constructor($$source = {}) {
        if (!("property" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["property"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {PropKind}
             */
            this["kind"] = PropKind.$zero;
        }
        if (!("display" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["list"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["num"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["bool"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["empty"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseCell instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseCell}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField3_0($$parsedSource["list"]);
        }
        return new BaseCell(/** @type {Partial<BaseCell>} */($$parsedSource));
    }
}

/**
 * BaseDef 是一个 .nvbase 文件的完整内容。
 * 
 * 命名没跟 schema.BaseDefinition 一致（那个是 Descriptor 变量名），
 * 避免同名标识符在两个包里指代不同东西。
 */
export class BaseDef {
    /**
     * Creates a new BaseDef instance.
     * @param {Partial<BaseDef>} [$$source = {}] - The source object to create the BaseDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 限定子目录，空 = 整个工作区
             * @member
             * @type {string | undefined}
             */
            this["folder"] = undefined;
        }
        if (!("filters" in $$source)) {
            /**
             * @member
             * @type {BaseFilterGroup}
             */
            this["filters"] = (new BaseFilterGroup());
        }
        if (!("views" in $$source)) {
            /**
             * @member
             * @type {BaseView[]}
             */
            this["views"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseDef}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField3_0($$parsedSource["filters"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField4_0($$parsedSource["views"]);
        }
        return new BaseDef(/** @type {Partial<BaseDef>} */($$parsedSource));
    }
}

/**
 * BaseFilter 是一条筛选条件。
 * 
 * Value 用字符串承载而不是 any：这个结构要穿过 JSON 落盘、再穿过 Wails 到前端，
 * any 在这条链路上会退化成 float64/string/bool，类型信息反而更乱。
 * 统一用字符串存原文，比较时按**目标属性的类型**强转 —— 类型的权威来源是数据，不是查询。
 */
export class BaseFilter {
    /**
     * Creates a new BaseFilter instance.
     * @param {Partial<BaseFilter>} [$$source = {}] - The source object to create the BaseFilter.
     */
    constructor($$source = {}) {
        if (!("property" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["property"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operator"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 仅 in / notIn 使用
             * @member
             * @type {string[] | undefined}
             */
            this["values"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseFilter}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new BaseFilter(/** @type {Partial<BaseFilter>} */($$parsedSource));
    }
}

/**
 * BaseFilterGroup 是可嵌套的条件组。
 */
export class BaseFilterGroup {
    /**
     * Creates a new BaseFilterGroup instance.
     * @param {Partial<BaseFilterGroup>} [$$source = {}] - The source object to create the BaseFilterGroup.
     */
    constructor($$source = {}) {
        if (!("conjunction" in $$source)) {
            /**
             * and（默认）| or
             * @member
             * @type {string}
             */
            this["conjunction"] = "";
        }
        if (!("conditions" in $$source)) {
            /**
             * @member
             * @type {BaseFilter[]}
             */
            this["conditions"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {BaseFilterGroup[]}
             */
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseFilterGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseFilterGroup}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField1_0($$parsedSource["conditions"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        return new BaseFilterGroup(/** @type {Partial<BaseFilterGroup>} */($$parsedSource));
    }
}

/**
 * BaseGroup 是分组结果的一组。
 */
export class BaseGroup {
    /**
     * Creates a new BaseGroup instance.
     * @param {Partial<BaseGroup>} [$$source = {}] - The source object to create the BaseGroup.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {(BaseRow | null)[]}
             */
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseGroup}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        return new BaseGroup(/** @type {Partial<BaseGroup>} */($$parsedSource));
    }
}

/**
 * BaseResult 是一次查询的完整输出。
 */
export class BaseResult {
    /**
     * Creates a new BaseResult instance.
     * @param {Partial<BaseResult>} [$$source = {}] - The source object to create the BaseResult.
     */
    constructor($$source = {}) {
        if (!("viewId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["viewId"] = "";
        }
        if (!("viewName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["viewName"] = "";
        }
        if (!("viewType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["viewType"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {(BaseRow | null)[]}
             */
            this["rows"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {(BaseGroup | null)[]}
             */
            this["groups"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("returned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["returned"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("scanned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scanned"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType12;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField4_0($$parsedSource["rows"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField5_0($$parsedSource["groups"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField10_0($$parsedSource["warnings"]);
        }
        return new BaseResult(/** @type {Partial<BaseResult>} */($$parsedSource));
    }
}

/**
 * BaseRow 是查询结果的一行（一篇笔记）。
 */
export class BaseRow {
    /**
     * Creates a new BaseRow instance.
     * @param {Partial<BaseRow>} [$$source = {}] - The source object to create the BaseRow.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("cells" in $$source)) {
            /**
             * @member
             * @type {BaseCell[]}
             */
            this["cells"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseRow}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField2_0($$parsedSource["cells"]);
        }
        return new BaseRow(/** @type {Partial<BaseRow>} */($$parsedSource));
    }
}

/**
 * BaseSort 是一条排序规则。
 */
export class BaseSort {
    /**
     * Creates a new BaseSort instance.
     * @param {Partial<BaseSort>} [$$source = {}] - The source object to create the BaseSort.
     */
    constructor($$source = {}) {
        if (!("property" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["property"] = "";
        }
        if (!("desc" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["desc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseSort instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseSort}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BaseSort(/** @type {Partial<BaseSort>} */($$parsedSource));
    }
}

/**
 * BaseSummary 是视图列表项（不含完整筛选配置，列表页不需要）。
 */
export class BaseSummary {
    /**
     * Creates a new BaseSummary instance.
     * @param {Partial<BaseSummary>} [$$source = {}] - The source object to create the BaseSummary.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["folder"] = undefined;
        }
        if (!("viewCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["viewCount"] = 0;
        }
        if (!("filterCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filterCount"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BaseSummary(/** @type {Partial<BaseSummary>} */($$parsedSource));
    }
}

/**
 * BaseView 是一个视图配置。
 */
export class BaseView {
    /**
     * Creates a new BaseView instance.
     * @param {Partial<BaseView>} [$$source = {}] - The source object to create the BaseView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * table | board | list
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["columns"] = [];
        }
        if (!("sort" in $$source)) {
            /**
             * @member
             * @type {BaseSort[]}
             */
            this["sort"] = [];
        }
        if (!("groupBy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupBy"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * 0 = 用默认上限
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BaseView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BaseView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("sort" in $$parsedSource) {
            $$parsedSource["sort"] = $$createField4_0($$parsedSource["sort"]);
        }
        return new BaseView(/** @type {Partial<BaseView>} */($$parsedSource));
    }
}

/**
 * BuiltinTemplate 描述一个内置模板。
 */
export class BuiltinTemplate {
    /**
     * Creates a new BuiltinTemplate instance.
     * @param {Partial<BuiltinTemplate>} [$$source = {}] - The source object to create the BuiltinTemplate.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("def" in $$source)) {
            /**
             * @member
             * @type {BaseDef}
             */
            this["def"] = (new BaseDef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuiltinTemplate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuiltinTemplate}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("def" in $$parsedSource) {
            $$parsedSource["def"] = $$createField3_0($$parsedSource["def"]);
        }
        return new BuiltinTemplate(/** @type {Partial<BuiltinTemplate>} */($$parsedSource));
    }
}

/**
 * CompileAllResult 是 CompileAll 的聚合结果，专为 Wails 绑定设计：
 * 返回单一结构体 + error（而非 Go 惯用的 (results, []error) 双返回值）。
 * 原因：Wails 会把多返回值序列化为元组，而 []error 是接口切片，
 * 每个 error 经 JSON 会退化成 {}，前端拿不到任何错误信息。
 * 这里用结构化的 CompileErrorItem 承载「路径 + 消息」，前端可逐条展示。
 */
export class CompileAllResult {
    /**
     * Creates a new CompileAllResult instance.
     * @param {Partial<CompileAllResult>} [$$source = {}] - The source object to create the CompileAllResult.
     */
    constructor($$source = {}) {
        if (!("Results" in $$source)) {
            /**
             * Results 编译成功的篇目。
             * @member
             * @type {(CompileResult | null)[]}
             */
            this["Results"] = [];
        }
        if (!("Errors" in $$source)) {
            /**
             * Errors 单篇失败明细（路径 + 原因），不阻断其他篇。
             * @member
             * @type {CompileErrorItem[]}
             */
            this["Errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompileAllResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Results" in $$parsedSource) {
            $$parsedSource["Results"] = $$createField0_0($$parsedSource["Results"]);
        }
        if ("Errors" in $$parsedSource) {
            $$parsedSource["Errors"] = $$createField1_0($$parsedSource["Errors"]);
        }
        return new CompileAllResult(/** @type {Partial<CompileAllResult>} */($$parsedSource));
    }
}

/**
 * CompileErrorItem 单篇编译失败的路径与原因。
 */
export class CompileErrorItem {
    /**
     * Creates a new CompileErrorItem instance.
     * @param {Partial<CompileErrorItem>} [$$source = {}] - The source object to create the CompileErrorItem.
     */
    constructor($$source = {}) {
        if (!("Path" in $$source)) {
            /**
             * Path 失败的 Inbox 相对路径。
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Error" in $$source)) {
            /**
             * Error 人类可读的错误原因。
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileErrorItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompileErrorItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompileErrorItem(/** @type {Partial<CompileErrorItem>} */($$parsedSource));
    }
}

/**
 * CompileOutput 是「知识编译」的结构化产出。
 */
export class CompileOutput {
    /**
     * Creates a new CompileOutput instance.
     * @param {Partial<CompileOutput>} [$$source = {}] - The source object to create the CompileOutput.
     */
    constructor($$source = {}) {
        if (!("TLDR" in $$source)) {
            /**
             * TLDR 一句话摘要，调用方约束模型控制在 200 字以内。
             * @member
             * @type {string}
             */
            this["TLDR"] = "";
        }
        if (!("Tags" in $$source)) {
            /**
             * Tags AI 建议的标签（已去重，不含前导 #）。
             * @member
             * @type {string[]}
             */
            this["Tags"] = [];
        }
        if (!("SuggestedLinks" in $$source)) {
            /**
             * SuggestedLinks AI 建议的双链目标，形如 "笔记标题"（不含 [[ ]]）。
             * @member
             * @type {string[]}
             */
            this["SuggestedLinks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileOutput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompileOutput}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField1_0($$parsedSource["Tags"]);
        }
        if ("SuggestedLinks" in $$parsedSource) {
            $$parsedSource["SuggestedLinks"] = $$createField2_0($$parsedSource["SuggestedLinks"]);
        }
        return new CompileOutput(/** @type {Partial<CompileOutput>} */($$parsedSource));
    }
}

/**
 * CompileResult 单篇笔记的编译结果。
 */
export class CompileResult {
    /**
     * Creates a new CompileResult instance.
     * @param {Partial<CompileResult>} [$$source = {}] - The source object to create the CompileResult.
     */
    constructor($$source = {}) {
        if (!("Source" in $$source)) {
            /**
             * Source 原始（Inbox 内）相对路径。
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Dest" in $$source)) {
            /**
             * Dest 编译后（Compiled 内）相对路径。
             * @member
             * @type {string}
             */
            this["Dest"] = "";
        }
        if (!("SnapshotID" in $$source)) {
            /**
             * SnapshotID 编译前建立的快照 ID，用于整体撤销。
             * @member
             * @type {string}
             */
            this["SnapshotID"] = "";
        }
        if (!("Output" in $$source)) {
            /**
             * Output AI 产出的结构化内容。
             * @member
             * @type {CompileOutput | null}
             */
            this["Output"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompileResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Output" in $$parsedSource) {
            $$parsedSource["Output"] = $$createField3_0($$parsedSource["Output"]);
        }
        return new CompileResult(/** @type {Partial<CompileResult>} */($$parsedSource));
    }
}

/**
 * DiffOp 表示 diff 中的一行操作
 */
export class DiffOp {
    /**
     * Creates a new DiffOp instance.
     * @param {Partial<DiffOp>} [$$source = {}] - The source object to create the DiffOp.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("oldLine" in $$source)) {
            /**
             * 1-based；insert 时为 0
             * @member
             * @type {number}
             */
            this["oldLine"] = 0;
        }
        if (!("newLine" in $$source)) {
            /**
             * 1-based；delete 时为 0
             * @member
             * @type {number}
             */
            this["newLine"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 仅 DiffGap 使用：折叠的行数
             * @member
             * @type {number | undefined}
             */
            this["count"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffOp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffOp}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffOp(/** @type {Partial<DiffOp>} */($$parsedSource));
    }
}

/**
 * FileNode 表示文件树中的一个节点（文件或文件夹）
 */
export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 相对于工作区根目录的路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("fullPath" in $$source)) {
            /**
             * 绝对路径
             * @member
             * @type {string}
             */
            this["fullPath"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(FileNode | null)[] | undefined}
             */
            this["children"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modTime"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField4_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

/**
 * GitStatus 是工作区的 Git 概况，供前端决定展示「初始化」还是「提交」。
 */
export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * 系统里是否有可用的 git
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("isRepo" in $$source)) {
            /**
             * 工作区是否已是 git 仓库
             * @member
             * @type {boolean}
             */
            this["isRepo"] = false;
        }
        if (!("branch" in $$source)) {
            /**
             * 当前分支（非仓库时为空）
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("changed" in $$source)) {
            /**
             * 已跟踪文件的变更数（含暂存）
             * @member
             * @type {number}
             */
            this["changed"] = 0;
        }
        if (!("untracked" in $$source)) {
            /**
             * 未跟踪文件数
             * @member
             * @type {number}
             */
            this["untracked"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

/**
 * GraphData 知识图谱数据
 */
export class GraphData {
    /**
     * Creates a new GraphData instance.
     * @param {Partial<GraphData>} [$$source = {}] - The source object to create the GraphData.
     */
    constructor($$source = {}) {
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {(GraphNode | null)[]}
             */
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            /**
             * @member
             * @type {(GraphEdge | null)[]}
             */
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new GraphData(/** @type {Partial<GraphData>} */($$parsedSource));
    }
}

/**
 * GraphEdge 表示一条双向链接
 */
export class GraphEdge {
    /**
     * Creates a new GraphEdge instance.
     * @param {Partial<GraphEdge>} [$$source = {}] - The source object to create the GraphEdge.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * 源节点 ID
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * 目标节点 ID
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphEdge}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge(/** @type {Partial<GraphEdge>} */($$parsedSource));
    }
}

/**
 * GraphNode 表示知识图谱中的一个笔记节点
 */
export class GraphNode {
    /**
     * Creates a new GraphNode instance.
     * @param {Partial<GraphNode>} [$$source = {}] - The source object to create the GraphNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 相对路径，作为唯一标识
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 笔记标题（文件名或首个 # 标题）
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 相对路径（未解析节点为 "unresolved:名称"）
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("degree" in $$source)) {
            /**
             * 连接数，用于节点大小
             * @member
             * @type {number}
             */
            this["degree"] = 0;
        }
        if (!("resolved" in $$source)) {
            /**
             * 是否为已存在的笔记（false 表示未解析的虚拟节点）
             * @member
             * @type {boolean}
             */
            this["resolved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode(/** @type {Partial<GraphNode>} */($$parsedSource));
    }
}

/**
 * ImportOptions 导入选项
 */
export class ImportOptions {
    /**
     * Creates a new ImportOptions instance.
     * @param {Partial<ImportOptions>} [$$source = {}] - The source object to create the ImportOptions.
     */
    constructor($$source = {}) {
        if (!("conflictStrategy" in $$source)) {
            /**
             * ConflictStrategy 冲突策略：skip=跳过 / rename=自动重命名 / overwrite=覆盖（默认 skip）
             * @member
             * @type {string}
             */
            this["conflictStrategy"] = "";
        }
        if (!("includeSubdirs" in $$source)) {
            /**
             * IncludeSubdirs 是否保留源目录的子目录结构（默认 true）
             * @member
             * @type {boolean}
             */
            this["includeSubdirs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportOptions(/** @type {Partial<ImportOptions>} */($$parsedSource));
    }
}

/**
 * ImportResult 导入结果统计
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("imported" in $$source)) {
            /**
             * 成功导入文件数
             * @member
             * @type {number}
             */
            this["imported"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 跳过文件数（冲突/非 md）
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("renamed" in $$source)) {
            /**
             * 冲突自动重命名数
             * @member
             * @type {number}
             */
            this["renamed"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * 失败明细（不中断整体导入）
             * @member
             * @type {string[]}
             */
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * LLMEndpointPreset 描述一个可一键填入的端点预设。
 */
export class LLMEndpointPreset {
    /**
     * Creates a new LLMEndpointPreset instance.
     * @param {Partial<LLMEndpointPreset>} [$$source = {}] - The source object to create the LLMEndpointPreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("requiresKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresKey"] = false;
        }
        if (!("hint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMEndpointPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMEndpointPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMEndpointPreset(/** @type {Partial<LLMEndpointPreset>} */($$parsedSource));
    }
}

/**
 * LLMProbeResult 连通性自检结果。
 */
export class LLMProbeResult {
    /**
     * Creates a new LLMProbeResult instance.
     * @param {Partial<LLMProbeResult>} [$$source = {}] - The source object to create the LLMProbeResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * 实际探测的地址
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("isLocal" in $$source)) {
            /**
             * 是否判定为本机端点（免鉴权）
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("models" in $$source)) {
            /**
             * 端点声明可用的模型（拉取失败则为空）
             * @member
             * @type {string[]}
             */
            this["models"] = [];
        }
        if (!("latencyMs" in $$source)) {
            /**
             * 往返耗时
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 失败原因或补充说明
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LLMProbeResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new LLMProbeResult(/** @type {Partial<LLMProbeResult>} */($$parsedSource));
    }
}

/**
 * LinkCandidate 是编辑器 [[ 自动补全的候选项。
 */
export class LinkCandidate {
    /**
     * Creates a new LinkCandidate instance.
     * @param {Partial<LinkCandidate>} [$$source = {}] - The source object to create the LinkCandidate.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * "file" | "heading"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * 相对路径，如 "Notes/foo.md"
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("fileBase" in $$source)) {
            /**
             * 无扩展名文件名，如 "foo"
             * @member
             * @type {string}
             */
            this["fileBase"] = "";
        }
        if (!("heading" in $$source)) {
            /**
             * heading 类型时为目标标题；file 类型为空
             * @member
             * @type {string}
             */
            this["heading"] = "";
        }
        if (!("display" in $$source)) {
            /**
             * 人类可读标签（下拉里展示）
             * @member
             * @type {string}
             */
            this["display"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinkCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkCandidate(/** @type {Partial<LinkCandidate>} */($$parsedSource));
    }
}

/**
 * PropKind 是属性值的推断类型。
 * 
 * 为什么必须带类型：Bases 的筛选与排序要按语义比较，不能一律当字符串。
 * 字符串比较下 "10" < "9"、"2026-01-02" 与 "2026-1-2" 不等价、
 * true 和 "true" 无法区分——这些在「按 rating 排序」「筛 published=true」
 * 这类真实用法里全是错的结果。
 * @readonly
 * @enum {string}
 */
export const PropKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindString 普通文本
     */
    KindString: "string",

    /**
     * KindNumber 整数或浮点
     */
    KindNumber: "number",

    /**
     * KindBool true / false / yes / no
     */
    KindBool: "bool",

    /**
     * KindDate 日期或日期时间
     */
    KindDate: "date",

    /**
     * KindList 数组（内联 [a, b] 或块式 - a）
     */
    KindList: "list",
};

/**
 * PropertyMeta 描述工作区里一个属性的统计信息，供前端属性选择器使用。
 */
export class PropertyMeta {
    /**
     * Creates a new PropertyMeta instance.
     * @param {Partial<PropertyMeta>} [$$source = {}] - The source object to create the PropertyMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * 出现最多的类型
             * @member
             * @type {PropKind}
             */
            this["kind"] = PropKind.$zero;
        }
        if (!("count" in $$source)) {
            /**
             * 有该属性的笔记数
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("implicit" in $$source)) {
            /**
             * 是否为 file.* / todo.* 隐式属性
             * @member
             * @type {boolean}
             */
            this["implicit"] = false;
        }
        if (!("samples" in $$source)) {
            /**
             * 最多 8 个样例值，便于填筛选条件
             * @member
             * @type {string[]}
             */
            this["samples"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PropertyMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PropertyMeta}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField4_0($$parsedSource["samples"]);
        }
        return new PropertyMeta(/** @type {Partial<PropertyMeta>} */($$parsedSource));
    }
}

/**
 * QnACitation 表示回答中引用的一处知识库内容
 */
export class QnACitation {
    /**
     * Creates a new QnACitation instance.
     * @param {Partial<QnACitation>} [$$source = {}] - The source object to create the QnACitation.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * 引用编号（从 1 开始，与回答中的 [n] 对应）
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * 文档相对路径
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * 文档标题
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * 命中片段摘要
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("heading" in $$source)) {
            /**
             * 以下两项是 P0-2 分块检索的产物，让引用能定位到具体章节而不是整篇。
             * 前端暂未使用，属于向前兼容地扩展（不读不影响既有行为）。
             * 该块所属的最近上级标题
             * @member
             * @type {string}
             */
            this["heading"] = "";
        }
        if (!("chunkIndex" in $$source)) {
            /**
             * 块在文档内的序号，从 0 开始
             * @member
             * @type {number}
             */
            this["chunkIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QnACitation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QnACitation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QnACitation(/** @type {Partial<QnACitation>} */($$parsedSource));
    }
}

/**
 * QnAResponse 是一次问答的完整结果
 */
export class QnAResponse {
    /**
     * Creates a new QnAResponse instance.
     * @param {Partial<QnAResponse>} [$$source = {}] - The source object to create the QnAResponse.
     */
    constructor($$source = {}) {
        if (!("answer" in $$source)) {
            /**
             * Markdown 格式的回答
             * @member
             * @type {string}
             */
            this["answer"] = "";
        }
        if (!("citations" in $$source)) {
            /**
             * 引用的文档列表
             * @member
             * @type {QnACitation[]}
             */
            this["citations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QnAResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QnAResponse}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField1_0($$parsedSource["citations"]);
        }
        return new QnAResponse(/** @type {Partial<QnAResponse>} */($$parsedSource));
    }
}

/**
 * Reminder 表示一个提醒
 */
export class Reminder {
    /**
     * Creates a new Reminder instance.
     * @param {Partial<Reminder>} [$$source = {}] - The source object to create the Reminder.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("remindAt" in $$source)) {
            /**
             * ISO 8601 格式
             * @member
             * @type {string}
             */
            this["remindAt"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Reminder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Reminder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Reminder(/** @type {Partial<Reminder>} */($$parsedSource));
    }
}

/**
 * RerankConfig 是 rerank 端点的连接配置（与 embedding / LLM 配置相互独立）。
 */
export class RerankConfig {
    /**
     * Creates a new RerankConfig instance.
     * @param {Partial<RerankConfig>} [$$source = {}] - The source object to create the RerankConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {RerankProvider}
             */
            this["provider"] = RerankProvider.$zero;
        }
        if (!("baseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseURL"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RerankConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RerankConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RerankConfig(/** @type {Partial<RerankConfig>} */($$parsedSource));
    }
}

/**
 * RerankProbeResult 重排端点连通性自检结果（镜像 LLMProbeResult）。
 * 供前端「设置 → 重排序」页的「测试连接」按钮使用，让 rerank 配置在保存前
 * 就被明确校验——避免 P1-3b 的静默失效（Ollama 无 /api/rerank，404 被降级逻辑吞掉）。
 */
export class RerankProbeResult {
    /**
     * Creates a new RerankProbeResult instance.
     * @param {Partial<RerankProbeResult>} [$$source = {}] - The source object to create the RerankProbeResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * 实际探测的地址（应与真实重排请求一致）
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }
        if (!("isLocal" in $$source)) {
            /**
             * 是否本机端点（免鉴权）
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("latencyMs" in $$source)) {
            /**
             * 往返耗时
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * 失败原因或可操作提示
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RerankProbeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RerankProbeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RerankProbeResult(/** @type {Partial<RerankProbeResult>} */($$parsedSource));
    }
}

/**
 * RerankProvider 标识重排序服务的厂商/协议。
 * @readonly
 * @enum {string}
 */
export const RerankProvider = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * RerankProviderOllama 本机 Ollama /api/rerank 端点（默认，免鉴权）。
     */
    RerankProviderOllama: "ollama",

    /**
     * RerankProviderCohere Cohere /v1/rerank 端点（需 API Key）。
     */
    RerankProviderCohere: "cohere",
};

/**
 * SearchIndexStats 描述索引的覆盖情况，供状态栏提示（P0-5）
 */
export class SearchIndexStats {
    /**
     * Creates a new SearchIndexStats instance.
     * @param {Partial<SearchIndexStats>} [$$source = {}] - The source object to create the SearchIndexStats.
     */
    constructor($$source = {}) {
        if (!("docCount" in $$source)) {
            /**
             * 已索引文档数
             * @member
             * @type {number}
             */
            this["docCount"] = 0;
        }
        if (!("tokenCount" in $$source)) {
            /**
             * 倒排表 token 数
             * @member
             * @type {number}
             */
            this["tokenCount"] = 0;
        }
        if (!("scanComplete" in $$source)) {
            /**
             * false = 触及 maxScanFiles 上限，仍有文件未扫
             * @member
             * @type {boolean}
             */
            this["scanComplete"] = false;
        }
        if (!("skippedCount" in $$source)) {
            /**
             * 因体积超过 maxSearchFileSize 被跳过的文件数
             * @member
             * @type {number}
             */
            this["skippedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchIndexStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchIndexStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchIndexStats(/** @type {Partial<SearchIndexStats>} */($$parsedSource));
    }
}

/**
 * SearchResult 表示一个搜索结果
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }
        if (!("matchCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["matchCount"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * P0-4：供前端「按最近修改」排序
             * @member
             * @type {string}
             */
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * Snapshot 表示一份历史版本的元数据（内容存在 objects 里，按 Hash 寻址）
 */
export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * 相对工作区路径，统一用 / 分隔
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("hash" in $$source)) {
            /**
             * 内容 sha256（内容寻址键）
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * 原始内容字节数（非压缩后）
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

/**
 * SnapshotDiff 是某个快照与目标版本（另一快照或当前文件）的差异
 */
export class SnapshotDiff {
    /**
     * Creates a new SnapshotDiff instance.
     * @param {Partial<SnapshotDiff>} [$$source = {}] - The source object to create the SnapshotDiff.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("fromId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromId"] = "";
        }
        if (!("toId" in $$source)) {
            /**
             * 空串表示「当前工作区文件」
             * @member
             * @type {string}
             */
            this["toId"] = "";
        }
        if (!("fromAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromAt"] = "";
        }
        if (!("toAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toAt"] = "";
        }
        if (!("ops" in $$source)) {
            /**
             * @member
             * @type {DiffOp[]}
             */
            this["ops"] = [];
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removed"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("identical" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["identical"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotDiff}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ops" in $$parsedSource) {
            $$parsedSource["ops"] = $$createField5_0($$parsedSource["ops"]);
        }
        return new SnapshotDiff(/** @type {Partial<SnapshotDiff>} */($$parsedSource));
    }
}

/**
 * SnapshotFileSummary 按文件聚合的快照概览，用于时间机器面板左侧文件列表
 */
export class SnapshotFileSummary {
    /**
     * Creates a new SnapshotFileSummary instance.
     * @param {Partial<SnapshotFileSummary>} [$$source = {}] - The source object to create the SnapshotFileSummary.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("latestAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestAt"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotFileSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotFileSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotFileSummary(/** @type {Partial<SnapshotFileSummary>} */($$parsedSource));
    }
}

/**
 * SnapshotRestoreResult 恢复结果。BackupID 是恢复前自动打的安全备份，
 * 让「恢复错了」也能再退回去——AI/批量改写场景下这一步是刚需。
 */
export class SnapshotRestoreResult {
    /**
     * Creates a new SnapshotRestoreResult instance.
     * @param {Partial<SnapshotRestoreResult>} [$$source = {}] - The source object to create the SnapshotRestoreResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("restoredId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["restoredId"] = "";
        }
        if (!("backupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupId"] = "";
        }
        if (!("bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotRestoreResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotRestoreResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotRestoreResult(/** @type {Partial<SnapshotRestoreResult>} */($$parsedSource));
    }
}

/**
 * SnapshotStats 历史库占用概览
 */
export class SnapshotStats {
    /**
     * Creates a new SnapshotStats instance.
     * @param {Partial<SnapshotStats>} [$$source = {}] - The source object to create the SnapshotStats.
     */
    constructor($$source = {}) {
        if (!("snapshots" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["snapshots"] = 0;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("objects" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["objects"] = 0;
        }
        if (!("diskBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotStats(/** @type {Partial<SnapshotStats>} */($$parsedSource));
    }
}

/**
 * TagFileInfo 表示包含某个标签的文件信息
 */
export class TagFileInfo {
    /**
     * Creates a new TagFileInfo instance.
     * @param {Partial<TagFileInfo>} [$$source = {}] - The source object to create the TagFileInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TagFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagFileInfo(/** @type {Partial<TagFileInfo>} */($$parsedSource));
    }
}

/**
 * TagInfo 表示一个标签及其使用次数
 */
export class TagInfo {
    /**
     * Creates a new TagInfo instance.
     * @param {Partial<TagInfo>} [$$source = {}] - The source object to create the TagInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TagInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagInfo(/** @type {Partial<TagInfo>} */($$parsedSource));
    }
}

/**
 * TaskInfo 是任务的对外快照（会被 Wails 序列化成前端 TS 类型）。
 */
export class TaskInfo {
    /**
     * Creates a new TaskInfo instance.
     * @param {Partial<TaskInfo>} [$$source = {}] - The source object to create the TaskInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskInfo(/** @type {Partial<TaskInfo>} */($$parsedSource));
    }
}

/**
 * TaskStatus 任务状态
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 已提交，等待并发名额
     */
    TaskPending: "pending",

    /**
     * 正在执行
     */
    TaskRunning: "running",

    /**
     * 正常完成
     */
    TaskSucceeded: "succeeded",

    /**
     * 返回错误
     */
    TaskFailed: "failed",

    /**
     * 被用户取消
     */
    TaskCancelled: "cancelled",
};

/**
 * TemplateInfo 描述一个可用模板。
 */
export class TemplateInfo {
    /**
     * Creates a new TemplateInfo instance.
     * @param {Partial<TemplateInfo>} [$$source = {}] - The source object to create the TemplateInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 模板名（文件名去扩展名），即模板 ID
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("variables" in $$source)) {
            /**
             * 需要用户填写的自定义变量（已排除内置）
             * @member
             * @type {string[]}
             */
            this["variables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemplateInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField1_0($$parsedSource["variables"]);
        }
        return new TemplateInfo(/** @type {Partial<TemplateInfo>} */($$parsedSource));
    }
}

/**
 * TodoItem 表示一个待办事项
 */
export class TodoItem {
    /**
     * Creates a new TodoItem instance.
     * @param {Partial<TodoItem>} [$$source = {}] - The source object to create the TodoItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("lineIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lineIndex"] = 0;
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("priority" in $$source)) {
            /**
             * high, medium, low
             * @member
             * @type {string}
             */
            this["priority"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TodoItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TodoItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TodoItem(/** @type {Partial<TodoItem>} */($$parsedSource));
    }
}

/**
 * TrashedFile 表示回收站中的文件
 */
export class TrashedFile {
    /**
     * Creates a new TrashedFile instance.
     * @param {Partial<TrashedFile>} [$$source = {}] - The source object to create the TrashedFile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("originalPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["originalPath"] = "";
        }
        if (!("deletedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deletedAt"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrashedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashedFile(/** @type {Partial<TrashedFile>} */($$parsedSource));
    }
}

/**
 * Workspace 表示一个知识库工作区
 */
export class Workspace {
    /**
     * Creates a new Workspace instance.
     * @param {Partial<Workspace>} [$$source = {}] - The source object to create the Workspace.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("lastOpenedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastOpenedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workspace}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Workspace(/** @type {Partial<Workspace>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = BaseFilterGroup.createFrom;
const $$createType2 = BaseView.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = BaseFilter.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType1);
const $$createType7 = BaseRow.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = BaseGroup.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = BaseCell.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = BaseSort.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = BaseDef.createFrom;
const $$createType18 = CompileResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = CompileErrorItem.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = CompileOutput.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = FileNode.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = GraphNode.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = GraphEdge.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = QnACitation.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = DiffOp.createFrom;
const $$createType37 = $Create.Array($$createType36);
