// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QnAService 提供基于 RAG（检索增强生成）的知识库问答能力。
 * 设计：
 *  1. 检索 —— 复用 searchindex 的内存反向索引（与全文搜索同一份缓存，增量更新），
 *     按「问题 token 与文档 token 的重合度」评分并取 Top-K；
 *  2. 生成 —— 将 Top-K 文档内容作为上下文注入 system prompt，
 *     调用 OpenAI 兼容 Chat Completions API 生成带 [n] 引用标注的回答。
 * 
 * API Key 仅由前端在调用时传入，Go 端不落盘存储，保障隐私。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer 对知识库提问并返回带引用的回答
 *   - apiKey: 用户 API Key（本地存储，不落盘）
 *   - baseURL: OpenAI 兼容接口地址
 *   - model: 模型名称
 *   - workspacePath: 工作区根目录
 *   - question: 用户问题
 */
export function Answer(apiKey: string, baseURL: string, model: string, workspacePath: string, question: string): $CancellablePromise<$models.QnAResponse | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.QnAService.Answer", apiKey, baseURL, model, workspacePath, question);
}
