// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QnAService 提供基于 RAG（检索增强生成）的知识库问答能力。
 * 设计：
 *  1. 检索 —— 复用 searchindex 的内存反向索引（与全文搜索同一份缓存，增量更新），
 *     按「问题 token 与文档 token 的重合度」评分并取 Top-K；
 *  2. 生成 —— 将 Top-K 文档内容作为上下文注入 system prompt，
 *     调用 OpenAI 兼容 Chat Completions API 生成带 [n] 引用标注的回答。
 * 
 * P1-3 增强：配置 embedding 端点后，检索在块级融合「向量 leg」（chromem 包装的
 * 语义检索）与既有 BM25 leg（RRF 加权）。未配置 embedding 时，融合层直接退化
 * 为纯 BM25，行为与 P0 结束态逐字节一致（红线 #1）。
 * 
 * API Key 仅由前端在调用时传入，Go 端不落盘存储，保障隐私。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer 对知识库提问并返回带引用的回答
 *   - apiKey: 用户 API Key（本地存储，不落盘）
 *   - baseURL: OpenAI 兼容接口地址（Chat/生成）
 *   - model: 模型名称
 *   - embBaseURL / embModel / embAPIKey: 语义检索用的 embedding 端点配置
 *     （与生成端点独立，P1-6 #2）。三者为空时向量 leg 不启用，退化为纯 BM25。
 *   - rerankCfg: 重排序端点配置（P1-3b，可选）。未配置时检索融合退化为纯 BM25 + 向量 RRF，
 *     与 P1-3 结束态一致；重排服务不可用时静默回退，不阻断问答。
 *   - workspacePath: 工作区根目录
 *   - question: 用户问题
 * 
 * 注：rerankCfg 用结构体而非 3~4 个裸 string 传入（对比 embedding 的三裸 string），
 * 是 P1-3 之后的演进——配置字段更多（provider/baseURL/model/apiKey）时，结构体比
 * 一长串位置参数更易读、不易错位。embedding 的裸 string 签名已在 P1-3 落地，不回溯重构。
 * @param {string} apiKey
 * @param {string} baseURL
 * @param {string} model
 * @param {string} embBaseURL
 * @param {string} embModel
 * @param {string} embAPIKey
 * @param {$models.RerankConfig} rerankCfg
 * @param {string} workspacePath
 * @param {string} question
 * @returns {$CancellablePromise<$models.QnAResponse | null>}
 */
export function Answer(apiKey, baseURL, model, embBaseURL, embModel, embAPIKey, rerankCfg, workspacePath, question) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.QnAService.Answer", apiKey, baseURL, model, embBaseURL, embModel, embAPIKey, rerankCfg, workspacePath, question);
}

/**
 * HybridSearch 是文档级混合检索，供前端搜索页语义增强使用（P1-3，P1-3b 增强）。
 * 
 * 融合 BM25 文档级排名与向量文档级排名（每个文档取最高块相似度），RRF 加权。
 * 未配置 embedding 时退化为纯 BM25 文档级检索，返回结构与 SearchService.Search 一致。
 * 
 * P1-3b：额外配置 rerank（rerankCfg 非空且 reranker 可用）时，在 RRF 融合后
 * 再用 cross-encoder 对候选文档做一遍重排，修正排序。rerank 不可用静默回退 RRF，
 * 行为与 P1-3 结束态一致。
 * @param {string} workspacePath
 * @param {string} query
 * @param {string} embBaseURL
 * @param {string} embModel
 * @param {string} embAPIKey
 * @param {$models.RerankConfig} rerankCfg
 * @returns {$CancellablePromise<($models.SearchResult | null)[] | null>}
 */
export function HybridSearch(workspacePath, query, embBaseURL, embModel, embAPIKey, rerankCfg) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.QnAService.HybridSearch", workspacePath, query, embBaseURL, embModel, embAPIKey, rerankCfg);
}
