// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReminderService 提供提醒管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddReminder 添加新提醒
 */
export function AddReminder(workspacePath: string, filePath: string, content: string, remindAt: string): $CancellablePromise<$models.Reminder | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReminderService.AddReminder", workspacePath, filePath, content, remindAt);
}

/**
 * DeleteReminder 删除提醒
 */
export function DeleteReminder(workspacePath: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReminderService.DeleteReminder", workspacePath, id);
}

/**
 * GetAllReminders 获取所有提醒
 */
export function GetAllReminders(workspacePath: string): $CancellablePromise<($models.Reminder | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReminderService.GetAllReminders", workspacePath);
}

/**
 * GetUpcomingReminders 获取即将到来的提醒（未来 24 小时内）
 */
export function GetUpcomingReminders(workspacePath: string): $CancellablePromise<($models.Reminder | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReminderService.GetUpcomingReminders", workspacePath);
}

/**
 * ToggleReminder 切换提醒完成状态
 */
export function ToggleReminder(workspacePath: string, id: string): $CancellablePromise<$models.Reminder | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReminderService.ToggleReminder", workspacePath, id);
}
