// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReminderService 提供提醒管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddReminder 添加新提醒
 * @param {string} workspacePath
 * @param {string} filePath
 * @param {string} content
 * @param {string} remindAt
 * @returns {$CancellablePromise<$models.Reminder | null>}
 */
export function AddReminder(workspacePath, filePath, content, remindAt) {
    return $Call.ByID(3720334263, workspacePath, filePath, content, remindAt).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteReminder 删除提醒
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteReminder(workspacePath, id) {
    return $Call.ByID(1642753243, workspacePath, id);
}

/**
 * GetAllReminders 获取所有提醒
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.Reminder | null)[]>}
 */
export function GetAllReminders(workspacePath) {
    return $Call.ByID(2411839232, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetUpcomingReminders 获取即将到来的提醒（未来 24 小时内）
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.Reminder | null)[]>}
 */
export function GetUpcomingReminders(workspacePath) {
    return $Call.ByID(3222954267, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ToggleReminder 切换提醒完成状态
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<$models.Reminder | null>}
 */
export function ToggleReminder(workspacePath, id) {
    return $Call.ByID(2592481672, workspacePath, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Reminder.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
