// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReportService 提供知识周报生成
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GenerateWeeklyReport 生成本周（ISO 周）知识周报并写入 Reports/ 目录。
 * 周报已存在时覆盖重写（重复点击生成是正常操作，不是冲突）。
 */
export function GenerateWeeklyReport(workspacePath: string, ai: $models.WeeklyReportAIConfig): $CancellablePromise<$models.WeeklyReportResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReportService.GenerateWeeklyReport", workspacePath, ai);
}
