// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService 提供批量总结与定期回顾
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GenerateReview 生成定期回顾笔记。
 * days 为回看窗口（30..366 之外收敛），近窗口内改动的笔记逐篇 AI 摘要
 * （单篇失败不影响其它篇），另附"旧笔记重温"清单（>90 天未改动、最久优先）。
 * 产物覆盖写 Reviews/回顾-<日期>.md（重复生成是正常操作）。
 */
export function GenerateReview(workspacePath: string, ai: $models.WeeklyReportAIConfig, days: number): $CancellablePromise<$models.ReviewResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReviewService.GenerateReview", workspacePath, ai, days);
}

/**
 * ScheduleWeeklyReview 预约下一次回顾提醒：下一个周一 09:00（本地时区）。
 * 今天是周一且已过 09:00 则预约下周一。提醒是一次性的——模型刻意不做
 * 重复调度（Reminder schema 保持简单），到点重新点一次即可。
 */
export function ScheduleWeeklyReview(workspacePath: string): $CancellablePromise<$models.Reminder | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.ReviewService.ScheduleWeeklyReview", workspacePath);
}
