// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 提供全文搜索功能，基于内存反向索引。
 * 首次搜索全量构建索引，后续仅按 modtime 增量更新变更文件，
 * 避免每次搜索都全量读盘。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIndexStats 返回当前工作区索引的覆盖情况。
 * 
 * 前端应当据此在状态栏提示用户「有 N 个文件未被索引」，
 * 而不是让超限静默发生。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<$models.SearchIndexStats | null>}
 */
export function GetIndexStats(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.GetIndexStats", workspacePath);
}

/**
 * Search 在工作区中搜索关键词
 * workspacePath: 工作区根目录
 * query: 搜索关键词
 * 返回匹配的文件列表（已按匹配次数降序、并截断到结果上限）
 * @param {string} workspacePath
 * @param {string} query
 * @returns {$CancellablePromise<($models.SearchResult | null)[] | null>}
 */
export function Search(workspacePath, query) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.Search", workspacePath, query);
}

/**
 * GetSearchSnippet 按需为单个结果生成片段（前端滚动到可视区时调用）。
 * 
 * Search/HybridSearch 只对前 N 条即时生成 snippet，其余留空；本方法供前端
 * 把留空结果滚入视区时补取，避免一次性读 200 篇正文拖慢首屏。
 * 口径与即时片段一致（首个查询 token 定位、半径 50）。
 * @param {string} workspacePath
 * @param {string} relPath
 * @param {string} query
 * @returns {$CancellablePromise<string>}
 */
export function GetSearchSnippet(workspacePath, relPath, query) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.GetSearchSnippet", workspacePath, relPath, query);
}
