// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 提供全文搜索功能，基于内存反向索引。
 * 首次搜索全量构建索引，后续仅按 modtime 增量更新变更文件，
 * 避免每次搜索都全量读盘。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIndexStats 返回当前工作区索引的覆盖情况。
 * 
 * 前端应当据此在状态栏提示用户「有 N 个文件未被索引」，
 * 而不是让超限静默发生。
 */
export function GetIndexStats(workspacePath: string): $CancellablePromise<$models.SearchIndexStats | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.GetIndexStats", workspacePath);
}

/**
 * GetSearchSnippet 按需为单个结果生成 snippet（前端滚动到可视区时调用）。
 * 
 * 只读取这一个文件的正文并定位片段，不拖累 Search/HybridSearch 的首屏延迟。
 * 与 Search 即时片段用同一套口径（首个查询 token 定位、半径 50），保证两者
 * 视觉一致。未配置查询或文档不在索引中时返回空串/报错，由调用方决定降级展示。
 */
export function GetSearchSnippet(workspacePath: string, relPath: string, query: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.GetSearchSnippet", workspacePath, relPath, query);
}

/**
 * Search 在工作区中搜索关键词
 * workspacePath: 工作区根目录
 * query: 搜索关键词
 * 返回匹配的文件列表（已按匹配次数降序、并截断到结果上限）
 */
export function Search(workspacePath: string, query: string): $CancellablePromise<($models.SearchResult | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.Search", workspacePath, query);
}
