// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 提供全文搜索功能，基于内存反向索引。
 * 首次搜索全量构建索引，后续仅按 modtime 增量更新变更文件，
 * 避免每次搜索都全量读盘。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetIndexStats 返回当前工作区索引的覆盖情况。
 * 
 * 前端应当据此在状态栏提示用户「有 N 个文件未被索引」，
 * 而不是让超限静默发生。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<$models.SearchIndexStats | null>}
 */
export function GetIndexStats(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.GetIndexStats", workspacePath);
}

/**
 * Search 在工作区中搜索关键词
 * workspacePath: 工作区根目录
 * query: 搜索关键词
 * 返回匹配的文件列表（已按匹配次数降序、并截断到结果上限）
 * @param {string} workspacePath
 * @param {string} query
 * @returns {$CancellablePromise<($models.SearchResult | null)[] | null>}
 */
export function Search(workspacePath, query) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.Search", workspacePath, query);
}
