// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 提供全文搜索功能，基于内存反向索引。
 * 首次搜索全量构建索引，后续仅按 modtime 增量更新变更文件，
 * 避免每次搜索都全量读盘。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Search 在工作区中搜索关键词
 * workspacePath: 工作区根目录
 * query: 搜索关键词
 * 返回匹配的文件列表（已按匹配次数降序、并截断到结果上限）
 */
export function Search(workspacePath: string, query: string): $CancellablePromise<($models.SearchResult | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SearchService.Search", workspacePath, query);
}
