// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService 提供版本快照的留存、查看、比对与恢复
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSnapshots 清空某文件（relativePath 为空则全工作区）的全部历史，返回删除条目数
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<number>}
 */
export function ClearSnapshots(workspacePath, relativePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ClearSnapshots", workspacePath, relativePath);
}

/**
 * CreateManualSnapshot 用户主动为当前文件打一个版本点（永不自动清理）
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.Snapshot | null>}
 */
export function CreateManualSnapshot(workspacePath, relativePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.CreateManualSnapshot", workspacePath, relativePath);
}

/**
 * DeleteSnapshot 删除单个快照条目，并回收不再被引用的对象
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSnapshot(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DeleteSnapshot", workspacePath, id);
}

/**
 * DiffSnapshots 比对同一文件的两个快照
 * @param {string} workspacePath
 * @param {string} fromID
 * @param {string} toID
 * @returns {$CancellablePromise<$models.SnapshotDiff | null>}
 */
export function DiffSnapshots(workspacePath, fromID, toID) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DiffSnapshots", workspacePath, fromID, toID);
}

/**
 * DiffWithCurrent 比对快照与当前工作区文件（时间机器最常用的视图）
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<$models.SnapshotDiff | null>}
 */
export function DiffWithCurrent(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DiffWithCurrent", workspacePath, id);
}

/**
 * GetSnapshotContent 取出某个快照的完整内容
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetSnapshotContent(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.GetSnapshotContent", workspacePath, id);
}

/**
 * GetSnapshotStats 统计历史库占用（objects 目录实际磁盘占用，非原始内容之和）
 * @param {string} workspacePath
 * @returns {$CancellablePromise<$models.SnapshotStats | null>}
 */
export function GetSnapshotStats(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.GetSnapshotStats", workspacePath);
}

/**
 * ListSnapshotFiles 按文件聚合快照概览，时间机器面板用它渲染左侧列表
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.SnapshotFileSummary | null)[] | null>}
 */
export function ListSnapshotFiles(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ListSnapshotFiles", workspacePath);
}

/**
 * ListSnapshots 列出快照，按时间倒序。relativePath 为空则返回全工作区。
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<($models.Snapshot | null)[] | null>}
 */
export function ListSnapshots(workspacePath, relativePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ListSnapshots", workspacePath, relativePath);
}

/**
 * PruneSnapshots 手动触发保留策略 + 对象回收，返回清理后的占用统计
 * @param {string} workspacePath
 * @returns {$CancellablePromise<$models.SnapshotStats | null>}
 */
export function PruneSnapshots(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.PruneSnapshots", workspacePath);
}

/**
 * RestoreSnapshot 把某个快照的内容写回工作区文件。
 * 写回前先把当前内容存成 restore 快照，保证「恢复错了还能再退回来」。
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<$models.SnapshotRestoreResult | null>}
 */
export function RestoreSnapshot(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.RestoreSnapshot", workspacePath, id);
}
