// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotService 提供版本快照的留存、查看、比对与恢复
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearSnapshots 清空某文件（relativePath 为空则全工作区）的全部历史，返回删除条目数
 */
export function ClearSnapshots(workspacePath: string, relativePath: string): $CancellablePromise<number> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ClearSnapshots", workspacePath, relativePath);
}

/**
 * CreateManualSnapshot 用户主动为当前文件打一个版本点（永不自动清理）
 */
export function CreateManualSnapshot(workspacePath: string, relativePath: string): $CancellablePromise<$models.Snapshot | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.CreateManualSnapshot", workspacePath, relativePath);
}

/**
 * DeleteSnapshot 删除单个快照条目，并回收不再被引用的对象
 */
export function DeleteSnapshot(workspacePath: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DeleteSnapshot", workspacePath, id);
}

/**
 * DiffSnapshots 比对同一文件的两个快照
 */
export function DiffSnapshots(workspacePath: string, fromID: string, toID: string): $CancellablePromise<$models.SnapshotDiff | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DiffSnapshots", workspacePath, fromID, toID);
}

/**
 * DiffWithCurrent 比对快照与当前工作区文件（时间机器最常用的视图）
 */
export function DiffWithCurrent(workspacePath: string, id: string): $CancellablePromise<$models.SnapshotDiff | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.DiffWithCurrent", workspacePath, id);
}

/**
 * GetSnapshotContent 取出某个快照的完整内容
 */
export function GetSnapshotContent(workspacePath: string, id: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.GetSnapshotContent", workspacePath, id);
}

/**
 * GetSnapshotStats 统计历史库占用（objects 目录实际磁盘占用，非原始内容之和）
 */
export function GetSnapshotStats(workspacePath: string): $CancellablePromise<$models.SnapshotStats | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.GetSnapshotStats", workspacePath);
}

/**
 * ListSnapshotFiles 按文件聚合快照概览，时间机器面板用它渲染左侧列表
 */
export function ListSnapshotFiles(workspacePath: string): $CancellablePromise<($models.SnapshotFileSummary | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ListSnapshotFiles", workspacePath);
}

/**
 * ListSnapshots 列出快照，按时间倒序。relativePath 为空则返回全工作区。
 */
export function ListSnapshots(workspacePath: string, relativePath: string): $CancellablePromise<($models.Snapshot | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.ListSnapshots", workspacePath, relativePath);
}

/**
 * PruneSnapshots 手动触发保留策略 + 对象回收，返回清理后的占用统计
 */
export function PruneSnapshots(workspacePath: string): $CancellablePromise<$models.SnapshotStats | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.PruneSnapshots", workspacePath);
}

/**
 * RestoreSnapshot 把某个快照的内容写回工作区文件。
 * 写回前先把当前内容存成 restore 快照，保证「恢复错了还能再退回来」。
 */
export function RestoreSnapshot(workspacePath: string, id: string): $CancellablePromise<$models.SnapshotRestoreResult | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SnapshotService.RestoreSnapshot", workspacePath, id);
}
