// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService 提供今日工作台聚合统计
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetTodayStats 汇总今日工作台数据。
 * 单次遍历工作区取 modtime（沿用搜索索引的隐藏目录口径），待办与提醒
 * 复用各自服务的既有接口；遍历失败返回错误，子项失败降级为零值不阻塞。
 */
export function GetTodayStats(workspacePath: string): $CancellablePromise<$models.TodayStats | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.StatsService.GetTodayStats", workspacePath);
}
