// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsService 提供今日工作台与报表中心聚合统计
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetTodayStats 汇总今日工作台数据。
 * 待办与提醒复用各自服务的既有接口；子项失败降级为零值不阻塞。
 */
export function GetTodayStats(workspacePath: string): $CancellablePromise<$models.TodayStats | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.StatsService.GetTodayStats", workspacePath);
}

/**
 * GetWritingActivity 返回报表中心的写作活跃数据（GitHub 风格热力图 +
 * 周/月汇总）。窗口为「含今天在内的最近 days 天」，days 越界收敛到 30..366。
 */
export function GetWritingActivity(workspacePath: string, days: number): $CancellablePromise<$models.WritingActivity | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.StatsService.GetWritingActivity", workspacePath, days);
}
