// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SummarizeService 提供 AI 笔记总结能力
 * 设计：调用 OpenAI 兼容的 Chat Completions API（任意兼容端点均可，如 OpenAI / DeepSeek / 本地 Ollama）。
 * API Key 仅由前端在调用时传入，Go 端不落盘存储，保障隐私。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Summarize 调用大模型生成笔记摘要
 *   - apiKey: 用户 API Key（本地存储，不落盘）
 *   - baseURL: 接口地址，例如 https://api.openai.com/v1 或 https://api.deepseek.com/v1
 *   - model: 模型名称
 *   - content: 待总结的笔记正文
 * 
 * 返回 Markdown 格式的摘要文本。
 */
export function Summarize(apiKey: string, baseURL: string, model: string, content: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.SummarizeService.Summarize", apiKey, baseURL, model, content);
}
