// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TagService 提供标签管理功能，带 30s TTL 缓存
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllTags 获取工作区中所有标签及其使用次数
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.TagInfo | null)[] | null>}
 */
export function GetAllTags(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TagService.GetAllTags", workspacePath);
}

/**
 * GetFilesByTag 获取包含指定标签的所有文件
 * @param {string} workspacePath
 * @param {string} tag
 * @returns {$CancellablePromise<($models.TagFileInfo | null)[] | null>}
 */
export function GetFilesByTag(workspacePath, tag) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TagService.GetFilesByTag", workspacePath, tag);
}

/**
 * InvalidateCache 清除指定工作区的标签缓存
 * @param {string} workspacePath
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateCache(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TagService.InvalidateCache", workspacePath);
}
