// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskService 管理进程内的异步任务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel 取消一个任务。
 * 
 * 返回 true 只表示"取消信号已发出"，不代表任务已经停下——
 * 任务体需要在自己的检查点响应 ctx.Done()。这是 Go 取消语义的固有约束。
 * 对已结束的任务调用返回 false（没什么可取消的）。
 * @param {string} taskID
 * @returns {$CancellablePromise<boolean>}
 */
export function Cancel(taskID) {
    return $Call.ByID(659531159, taskID);
}

/**
 * CancelAll 取消所有未结束的任务，返回实际发出取消信号的数量。
 * 
 * 用于"关闭工作区 / 退出应用"这类场景：没必要让后台任务继续跑，
 * 它们操作的目标马上就不存在了。
 * @returns {$CancellablePromise<number>}
 */
export function CancelAll() {
    return $Call.ByID(3938360850);
}

/**
 * GetTask 查询单个任务；不存在返回 nil。
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.TaskInfo | null>}
 */
export function GetTask(taskID) {
    return $Call.ByID(2132605098, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListTasks 返回全部任务快照，按提交顺序排列。
 * @returns {$CancellablePromise<($models.TaskInfo | null)[]>}
 */
export function ListTasks() {
    return $Call.ByID(3661650125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Wait 等待所有任务结束。主要用于测试与优雅退出。
 * @returns {$CancellablePromise<void>}
 */
export function Wait() {
    return $Call.ByID(1532524308);
}

// Private type creation functions
const $$createType0 = $models.TaskInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
