// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemplateService 提供模板列表与从模板创建笔记。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFromTemplate 用模板创建笔记：渲染占位符 → 经 FileService 落盘。
 * targetRelativePath 是相对工作区的目标路径（含 .md），{{title}} 取其去扩展名的文件名。
 * 返回创建好的文件节点；目标已存在时由 FileService 报错。
 * @param {string} workspacePath
 * @param {string} templateName
 * @param {string} targetRelativePath
 * @param {{ [_ in string]?: string } | null} variables
 * @returns {$CancellablePromise<$models.FileNode | null>}
 */
export function CreateFromTemplate(workspacePath, templateName, targetRelativePath, variables) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TemplateService.CreateFromTemplate", workspacePath, templateName, targetRelativePath, variables);
}

/**
 * GetTemplateContent 返回模板原文（前端预览用）。
 * @param {string} workspacePath
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetTemplateContent(workspacePath, name) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TemplateService.GetTemplateContent", workspacePath, name);
}

/**
 * ListTemplates 列出工作区全部模板（按名称排序）。
 * Templates/ 目录不存在时返回空列表——这是全新工作区的正常状态，不是错误。
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.TemplateInfo | null)[] | null>}
 */
export function ListTemplates(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TemplateService.ListTemplates", workspacePath);
}
