// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TodoService 提供待办事项管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAllTodos 获取工作区中所有待办事项
 */
export function GetAllTodos(workspacePath: string): $CancellablePromise<($models.TodoItem | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TodoService.GetAllTodos", workspacePath);
}

/**
 * GetTodoStats 获取待办事项统计
 */
export function GetTodoStats(workspacePath: string): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TodoService.GetTodoStats", workspacePath);
}

/**
 * ToggleTodo 切换待办事项的完成状态
 */
export function ToggleTodo(workspacePath: string, filePath: string, lineIndex: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TodoService.ToggleTodo", workspacePath, filePath, lineIndex);
}
