// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrashService 提供回收站管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EmptyTrash 清空回收站
 */
export function EmptyTrash(workspacePath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.EmptyTrash", workspacePath);
}

/**
 * GetTrashStats 获取回收站统计
 */
export function GetTrashStats(workspacePath: string): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.GetTrashStats", workspacePath);
}

/**
 * GetTrashedFiles 获取回收站中的所有文件
 */
export function GetTrashedFiles(workspacePath: string): $CancellablePromise<($models.TrashedFile | null)[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.GetTrashedFiles", workspacePath);
}

/**
 * MoveToTrash 移动文件到回收站
 */
export function MoveToTrash(workspacePath: string, relativePath: string): $CancellablePromise<$models.TrashedFile | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.MoveToTrash", workspacePath, relativePath);
}

/**
 * PermanentlyDelete 永久删除回收站中的文件
 */
export function PermanentlyDelete(workspacePath: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.PermanentlyDelete", workspacePath, id);
}

/**
 * RestoreFromTrash 从回收站恢复文件
 */
export function RestoreFromTrash(workspacePath: string, id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.RestoreFromTrash", workspacePath, id);
}
