// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrashService 提供回收站管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EmptyTrash 清空回收站
 * @param {string} workspacePath
 * @returns {$CancellablePromise<void>}
 */
export function EmptyTrash(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.EmptyTrash", workspacePath);
}

/**
 * GetTrashStats 获取回收站统计
 * @param {string} workspacePath
 * @returns {$CancellablePromise<{ [_ in string]?: number } | null>}
 */
export function GetTrashStats(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.GetTrashStats", workspacePath);
}

/**
 * GetTrashedFiles 获取回收站中的所有文件
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.TrashedFile | null)[] | null>}
 */
export function GetTrashedFiles(workspacePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.GetTrashedFiles", workspacePath);
}

/**
 * MoveToTrash 移动文件到回收站
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.TrashedFile | null>}
 */
export function MoveToTrash(workspacePath, relativePath) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.MoveToTrash", workspacePath, relativePath);
}

/**
 * PermanentlyDelete 永久删除回收站中的文件
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function PermanentlyDelete(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.PermanentlyDelete", workspacePath, id);
}

/**
 * RestoreFromTrash 从回收站恢复文件
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFromTrash(workspacePath, id) {
    return $Call.ByName("github.com/notevault/notevault/internal/service.TrashService.RestoreFromTrash", workspacePath, id);
}
