// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrashService 提供回收站管理功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EmptyTrash 清空回收站
 * @param {string} workspacePath
 * @returns {$CancellablePromise<void>}
 */
export function EmptyTrash(workspacePath) {
    return $Call.ByID(371602385, workspacePath);
}

/**
 * GetTrashStats 获取回收站统计
 * @param {string} workspacePath
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetTrashStats(workspacePath) {
    return $Call.ByID(1208299981, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTrashedFiles 获取回收站中的所有文件
 * @param {string} workspacePath
 * @returns {$CancellablePromise<($models.TrashedFile | null)[]>}
 */
export function GetTrashedFiles(workspacePath) {
    return $Call.ByID(4284665486, workspacePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MoveToTrash 移动文件到回收站
 * @param {string} workspacePath
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.TrashedFile | null>}
 */
export function MoveToTrash(workspacePath, relativePath) {
    return $Call.ByID(236188982, workspacePath, relativePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PermanentlyDelete 永久删除回收站中的文件
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function PermanentlyDelete(workspacePath, id) {
    return $Call.ByID(815748930, workspacePath, id);
}

/**
 * RestoreFromTrash 从回收站恢复文件
 * @param {string} workspacePath
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RestoreFromTrash(workspacePath, id) {
    return $Call.ByID(1270173196, workspacePath, id);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.TrashedFile.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
