// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService 管理工作区的创建、打开、删除和持久化
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateWorkspace 创建一个新工作区
 * name: 工作区名称
 * path: 工作区文件夹路径（如果文件夹不存在则创建）
 * 如果路径已存在工作区，则更新名称和最后打开时间，返回已有工作区
 */
export function CreateWorkspace(name: string, path: string): $CancellablePromise<$models.Workspace | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.CreateWorkspace", name, path);
}

/**
 * DeleteWorkspace 从列表中删除工作区（不删除实际文件）
 */
export function DeleteWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.DeleteWorkspace", workspaceID);
}

/**
 * GetCurrentWorkspace 获取当前打开的工作区
 */
export function GetCurrentWorkspace(): $CancellablePromise<$models.Workspace | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.GetCurrentWorkspace");
}

/**
 * GetWorkspaceByID 根据 ID 获取工作区
 */
export function GetWorkspaceByID(workspaceID: string): $CancellablePromise<$models.Workspace | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.GetWorkspaceByID", workspaceID);
}

/**
 * ListWorkspaces 获取所有工作区列表
 */
export function ListWorkspaces(): $CancellablePromise<$models.Workspace[] | null> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.ListWorkspaces");
}

/**
 * SetCurrentWorkspace 设置当前工作区
 */
export function SetCurrentWorkspace(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/service.WorkspaceService.SetCurrentWorkspace", workspaceID);
}
