// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService 管理工作区的创建、打开、删除和持久化
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateWorkspace 创建一个新工作区
 * name: 工作区名称
 * path: 工作区文件夹路径（如果文件夹不存在则创建）
 * 如果路径已存在工作区，则更新名称和最后打开时间，返回已有工作区
 * @param {string} name
 * @param {string} path
 * @returns {$CancellablePromise<$models.Workspace | null>}
 */
export function CreateWorkspace(name, path) {
    return $Call.ByID(4272592192, name, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteWorkspace 从列表中删除工作区（不删除实际文件）
 * @param {string} workspaceID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspace(workspaceID) {
    return $Call.ByID(955151957, workspaceID);
}

/**
 * GetCurrentWorkspace 获取当前打开的工作区
 * @returns {$CancellablePromise<$models.Workspace | null>}
 */
export function GetCurrentWorkspace() {
    return $Call.ByID(3630187259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetWorkspaceByID 根据 ID 获取工作区
 * @param {string} workspaceID
 * @returns {$CancellablePromise<$models.Workspace | null>}
 */
export function GetWorkspaceByID(workspaceID) {
    return $Call.ByID(3454076450, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListWorkspaces 获取所有工作区列表
 * @returns {$CancellablePromise<$models.Workspace[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(2455890753).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetCurrentWorkspace 设置当前工作区
 * @param {string} workspaceID
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentWorkspace(workspaceID) {
    return $Call.ByID(3178077255, workspaceID);
}

// Private type creation functions
const $$createType0 = $models.Workspace.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
