// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是 NoteVault 的核心应用服务
 * 后续 Phase 会拆分为多个独立 Service（FileService、SearchService 等）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ForceQuit 立即终止进程，跳过任何 graceful shutdown。
 * 用于 Wails app.Quit() 卡死时的兜底（已知 beta 版本 Quit 在某些场景下会阻塞）。
 */
export function ForceQuit(): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/app.AppService.ForceQuit");
}

/**
 * GetAppName 返回应用名称
 */
export function GetAppName(): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/app.AppService.GetAppName");
}

/**
 * GetVersion 返回应用版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/app.AppService.GetVersion");
}

/**
 * OpenFileDialog 弹出系统原生对话框选择单个文件，可指定过滤器（如 "*.zip"），返回绝对路径
 */
export function OpenFileDialog(filter: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/app.AppService.OpenFileDialog", filter);
}

/**
 * OpenFolderDialog 弹出系统原生对话框选择文件夹，返回绝对路径（用户取消返回空串）
 */
export function OpenFolderDialog(): $CancellablePromise<string> {
    return $Call.ByName("github.com/notevault/notevault/internal/app.AppService.OpenFolderDialog");
}
