package service

import (
	"errors"
	"fmt"
	"os"
)

var errSourceGeneratedPersistence = errors.New("生成附加文件或其来源记录保存失败")

func sourceSetGenerated(records []sourceGeneratedRecord, record sourceGeneratedRecord) []sourceGeneratedRecord {
	out := append([]sourceGeneratedRecord{}, records...)
	for i := range out {
		if out[i].Path == record.Path {
			out[i] = record
			return out
		}
	}
	return append(out, record)
}

func sourceRemoveGenerated(records []sourceGeneratedRecord, relative string) []sourceGeneratedRecord {
	out := make([]sourceGeneratedRecord, 0, len(records))
	for _, record := range records {
		if record.Path != relative {
			out = append(out, record)
		}
	}
	return out
}

// A pending reservation is evidence of this pipeline's planned creation. An
// existing note without one is authored/legacy content, even if its bytes happen
// to match a current template. Confirmed generation hashes describe the initial
// generated bytes and are not refreshed when a user edits the file.
func sourceRecoverGenerated(root *os.Root, target, relative string) (bool, string, error) {
	manifest, before, ledgerExists, err := sourceLoadManifest(root, target)
	if err != nil {
		return false, "", err
	}
	content, exists, err := sourceReadRoot(root, relative, sourceMaxFileBytes)
	if err != nil || !exists {
		return exists, "", err
	}
	for _, record := range manifest.PendingGenerated {
		if record.Path != relative {
			continue
		}
		warning := ""
		if sourceChecksum(content) == record.SHA256 {
			manifest.Generated = sourceSetGenerated(manifest.Generated, record)
		} else {
			warning = "已保留当前文件：" + relative + "（内容在生成记录确认前已修改，未标记为本次生成）"
		}
		manifest.PendingGenerated = sourceRemoveGenerated(manifest.PendingGenerated, relative)
		update, err := sourcePrepareManifestUpdate(target, manifest, before, ledgerExists)
		if err != nil {
			return true, "", err
		}
		if err := update.save(root); err != nil {
			return true, "", err
		}
		return true, warning, nil
	}
	return true, "", nil
}

type sourceGeneratedWrite struct {
	path             string
	data             []byte
	reserve, confirm sourceManifestUpdate
}

func sourcePrepareGenerated(root *os.Root, target, relative, role string, data []byte) (sourceGeneratedWrite, error) {
	manifest, before, ledgerExists, err := sourceLoadManifest(root, target)
	if err != nil {
		return sourceGeneratedWrite{}, err
	}
	if _, exists, err := sourceReadRoot(root, relative, sourceMaxFileBytes); err != nil {
		return sourceGeneratedWrite{}, err
	} else if exists {
		return sourceGeneratedWrite{}, fmt.Errorf("生成附加文件已存在，已保留当前内容：%s", relative)
	}
	record := sourceGeneratedRecord{Path: relative, SHA256: sourceChecksum(data), Role: role}
	manifest.PendingGenerated = sourceSetGenerated(manifest.PendingGenerated, record)
	reserve, err := sourcePrepareManifestUpdate(target, manifest, before, ledgerExists)
	if err != nil {
		return sourceGeneratedWrite{}, err
	}
	manifest.Generated = sourceSetGenerated(manifest.Generated, record)
	manifest.PendingGenerated = sourceRemoveGenerated(manifest.PendingGenerated, relative)
	// Preflight both serialized states before touching the generated file.
	confirm, err := sourcePrepareManifestUpdate(target, manifest, reserve.after, true)
	if err != nil {
		return sourceGeneratedWrite{}, err
	}
	return sourceGeneratedWrite{path: relative, data: data, reserve: reserve, confirm: confirm}, nil
}

func (write sourceGeneratedWrite) save(root *os.Root) (bool, error) {
	if err := write.reserve.save(root); err != nil {
		return false, err
	}
	if err := sourceWriteRoot(root, write.path, write.data, nil, false); err != nil {
		return false, err
	}
	// The file is already real even if confirmation fails. Retain the pending
	// reservation so another service instance can confirm its matching bytes.
	return true, write.confirm.save(root)
}

func sourceWriteGenerated(root *os.Root, target, relative, role string, data []byte) (bool, error) {
	write, err := sourcePrepareGenerated(root, target, relative, role, data)
	if err != nil {
		return false, err
	}
	return write.save(root)
}
