// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ErrorMonitor 错误监控服务
 * 同时落地到本地日志文件（轮转）与可选的 Sentry 上报。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../core/models.js";

/**
 * ReportError 接收前端上报的错误事件
 */
export function ReportError(report: core$0.ErrorReport): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/infra/monitor.ErrorMonitor.ReportError", report);
}

/**
 * UpdateConfig 更新配置（运行时切换 DSN / 开关本地日志）
 */
export function UpdateConfig(cfg: core$0.ErrorMonitorConfig): $CancellablePromise<void> {
    return $Call.ByName("github.com/notevault/notevault/internal/infra/monitor.ErrorMonitor.UpdateConfig", cfg);
}
