// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    PluginTrust
} from "./models.js";

import * as $models from "./models.js";

/**
 * ErrorMonitorConfig 错误监控配置
 * 上移至 core：被 Reporter 端口的 UpdateConfig 方法引用（同 ErrorReport 的处理），
 * 避免 service 反向依赖 monitor。
 * @typedef {$models.ErrorMonitorConfig} ErrorMonitorConfig
 */

/**
 * ErrorReport 前端上报的错误事件
 * 上移至 core：被 Reporter 端口接口（service 层 ports.go）与 infra/monitor 共同引用，
 * 避免 service 反向依赖 monitor。
 * @typedef {$models.ErrorReport} ErrorReport
 */

/**
 * PluginInfo 插件完整信息（清单 + 运行时状态 + 元数据）
 * 上移至 core：被 PluginOperator 端口接口（service 层 ports.go）引用，
 * 避免 service 反向依赖 plugin。
 * @typedef {$models.PluginInfo} PluginInfo
 */

/**
 * PluginManifest 插件清单（从插件文件首部 front matter 解析）
 * @typedef {$models.PluginManifest} PluginManifest
 */
