// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ErrorMonitorConfig 错误监控配置
 * 上移至 core：被 Reporter 端口的 UpdateConfig 方法引用（同 ErrorReport 的处理），
 * 避免 service 反向依赖 monitor。
 */
export class ErrorMonitorConfig {
    /**
     * Creates a new ErrorMonitorConfig instance.
     * @param {Partial<ErrorMonitorConfig>} [$$source = {}] - The source object to create the ErrorMonitorConfig.
     */
    constructor($$source = {}) {
        if (!("sentryDsn" in $$source)) {
            /**
             * SentryDSN Sentry DSN，空表示不上报到 Sentry（仅本地日志）
             * @member
             * @type {string}
             */
            this["sentryDsn"] = "";
        }
        if (!("enableLocalLog" in $$source)) {
            /**
             * EnableLocalLog 是否写入本地日志文件（默认 true）
             * @member
             * @type {boolean}
             */
            this["enableLocalLog"] = false;
        }
        if (!("appVersion" in $$source)) {
            /**
             * AppVersion 应用版本号（用于上报事件）
             * @member
             * @type {string}
             */
            this["appVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorMonitorConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ErrorMonitorConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorMonitorConfig(/** @type {Partial<ErrorMonitorConfig>} */($$parsedSource));
    }
}

/**
 * ErrorReport 前端上报的错误事件
 * 上移至 core：被 Reporter 端口接口（service 层 ports.go）与 infra/monitor 共同引用，
 * 避免 service 反向依赖 monitor。
 */
export class ErrorReport {
    /**
     * Creates a new ErrorReport instance.
     * @param {Partial<ErrorReport>} [$$source = {}] - The source object to create the ErrorReport.
     */
    constructor($$source = {}) {
        if (!("message" in $$source)) {
            /**
             * Message 错误主信息（前端 new Error().message）
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Stack 错误堆栈（前端 new Error().stack）
             * @member
             * @type {string | undefined}
             */
            this["stack"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Source 错误来源（filename:line:col）
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Level 等级：info / warning / error / fatal（默认 error）
             * @member
             * @type {string | undefined}
             */
            this["level"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tags 额外标签（用于 Sentry 事件分组）
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Extra 额外上下文（不参与分组）
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["extra"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * UserAgent 用户代理字符串（前端 navigator.userAgent）
             * @member
             * @type {string | undefined}
             */
            this["userAgent"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Timestamp 触发时间（前端 Date.now() 毫秒，0 表示让后端补时间戳）
             * @member
             * @type {number | undefined}
             */
            this["timestamp"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ErrorReport}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField5_0($$parsedSource["extra"]);
        }
        return new ErrorReport(/** @type {Partial<ErrorReport>} */($$parsedSource));
    }
}

/**
 * PluginInfo 插件完整信息（清单 + 运行时状态 + 元数据）
 * 上移至 core：被 PluginOperator 端口接口（service 层 ports.go）引用，
 * 避免 service 反向依赖 plugin。
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {PluginManifest}
             */
            this["manifest"] = (new PluginManifest());
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("hash" in $$source)) {
            /**
             * sha256 摘要前 16 字符
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("source" in $$source)) {
            /**
             * 完整源码（前端预览用）
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("hasError" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasError"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["loadError"] = undefined;
        }
        if (!("trustGranted" in $$source)) {
            /**
             * TrustGranted 用户是否已授权该插件以 TrustFull 等级运行。
             * 仅当 Manifest.Trust == TrustFull 时有意义；授权与 Hash 绑定，
             * 源码变更后 Hash 对不上，此项会自动回落为 false。
             * @member
             * @type {boolean}
             */
            this["trustGranted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

/**
 * PluginManifest 插件清单（从插件文件首部 front matter 解析）
 */
export class PluginManifest {
    /**
     * Creates a new PluginManifest instance.
     * @param {Partial<PluginManifest>} [$$source = {}] - The source object to create the PluginManifest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["homepage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Trust 请求的信任等级，缺省按 TrustSandbox 处理。
             * 声明为 full 的插件在获得用户显式授权前，仍按沙箱等级运行。
             * @member
             * @type {PluginTrust | undefined}
             */
            this["trust"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginManifest}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField6_0($$parsedSource["permissions"]);
        }
        return new PluginManifest(/** @type {Partial<PluginManifest>} */($$parsedSource));
    }
}

/**
 * PluginTrust 插件请求的信任等级
 * @readonly
 * @enum {string}
 */
export const PluginTrust = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * TrustSandbox 默认等级：插件在 Web Worker 沙箱内运行，只能使用 manifest 声明的
     * 能力，且网络、本地存储、嵌套 Worker 均被禁用。绝大多数插件应停留在此等级。
     */
    TrustSandbox: "sandbox",

    /**
     * TrustFull 完全信任：插件在主进程（WebView）上下文运行，可访问界面与完整的
     * notevault 运行时对象。
     * 
     * 这不是插件自己声明了就能生效的等级——必须由用户逐插件显式授权，
     * 且授权与源码哈希绑定：插件一旦更新，授权自动失效、需要重新确认，
     * 防止"先以无害版本骗取授权、再通过更新投递恶意代码"。
     */
    TrustFull: "full",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = PluginManifest.createFrom;
const $$createType3 = $Create.Array($Create.Any);
